//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.Model.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Cement {
        
        /// <summary>
        ///   Looks up a localized string similar to: آدرس دقیق
        /// </summary>
        public static string Address([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Cement.Address;
            }
            return global::Resources.Model.Cement.ResourceManager.GetString("Address", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: مبلغ پرداخت
        /// </summary>
        public static string AmountPaid([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Cement.AmountPaid;
            }
            return global::Resources.Model.Cement.ResourceManager.GetString("AmountPaid", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: موبایل خریدار
        /// </summary>
        public static string BuyerMobile([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Cement.BuyerMobile;
            }
            return global::Resources.Model.Cement.ResourceManager.GetString("BuyerMobile", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: شهر تخلیه
        /// </summary>
        public static string City([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Cement.City;
            }
            return global::Resources.Model.Cement.ResourceManager.GetString("City", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: نام کارخانه
        /// </summary>
        public static string FactoryName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Cement.FactoryName;
            }
            return global::Resources.Model.Cement.ResourceManager.GetString("FactoryName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: شماره فاکتور
        /// </summary>
        public static string InvoiceNumber([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Cement.InvoiceNumber;
            }
            return global::Resources.Model.Cement.ResourceManager.GetString("InvoiceNumber", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: نوع بسته بندی
        /// </summary>
        public static string PackageType([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Cement.PackageType;
            }
            return global::Resources.Model.Cement.ResourceManager.GetString("PackageType", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: نام کالا
        /// </summary>
        public static string ProductName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Cement.ProductName;
            }
            return global::Resources.Model.Cement.ResourceManager.GetString("ProductName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: نوع کالا
        /// </summary>
        public static string ProductType([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Cement.ProductType;
            }
            return global::Resources.Model.Cement.ResourceManager.GetString("ProductType", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: استان تخلیه
        /// </summary>
        public static string Province([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Cement.Province;
            }
            return global::Resources.Model.Cement.ResourceManager.GetString("Province", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: شهر تخلیه
        /// </summary>
        public static string StringCity([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Cement.StringCity;
            }
            return global::Resources.Model.Cement.ResourceManager.GetString("StringCity", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: نام کارخانه
        /// </summary>
        public static string StringFactoryName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Cement.StringFactoryName;
            }
            return global::Resources.Model.Cement.ResourceManager.GetString("StringFactoryName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: زمان ثبت
        /// </summary>
        public static string StringInsertDateTime([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Cement.StringInsertDateTime;
            }
            return global::Resources.Model.Cement.ResourceManager.GetString("StringInsertDateTime", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: نوع بسته بندی
        /// </summary>
        public static string StringPackageType([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Cement.StringPackageType;
            }
            return global::Resources.Model.Cement.ResourceManager.GetString("StringPackageType", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: نام کالا
        /// </summary>
        public static string StringProductName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Cement.StringProductName;
            }
            return global::Resources.Model.Cement.ResourceManager.GetString("StringProductName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: نوع کالا
        /// </summary>
        public static string StringProductType([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Cement.StringProductType;
            }
            return global::Resources.Model.Cement.ResourceManager.GetString("StringProductType", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: استان تخلیه
        /// </summary>
        public static string StringProvince([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Cement.StringProvince;
            }
            return global::Resources.Model.Cement.ResourceManager.GetString("StringProvince", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تناژ
        /// </summary>
        public static string StringTonnage([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Cement.StringTonnage;
            }
            return global::Resources.Model.Cement.ResourceManager.GetString("StringTonnage", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تناژ
        /// </summary>
        public static string Tonnage([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Cement.Tonnage;
            }
            return global::Resources.Model.Cement.ResourceManager.GetString("Tonnage", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: روستای تخلیه
        /// </summary>
        public static string Village([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Cement.Village;
            }
            return global::Resources.Model.Cement.ResourceManager.GetString("Village", resourceCulture);
        }
    }
}
namespace Resources.Model.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class CementKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: آدرس دقیق
        /// </summary>
        public const string Address = "Address";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: مبلغ پرداخت
        /// </summary>
        public const string AmountPaid = "AmountPaid";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: موبایل خریدار
        /// </summary>
        public const string BuyerMobile = "BuyerMobile";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: شهر تخلیه
        /// </summary>
        public const string City = "City";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: نام کارخانه
        /// </summary>
        public const string FactoryName = "FactoryName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: شماره فاکتور
        /// </summary>
        public const string InvoiceNumber = "InvoiceNumber";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: نوع بسته بندی
        /// </summary>
        public const string PackageType = "PackageType";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: نام کالا
        /// </summary>
        public const string ProductName = "ProductName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: نوع کالا
        /// </summary>
        public const string ProductType = "ProductType";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: استان تخلیه
        /// </summary>
        public const string Province = "Province";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: شهر تخلیه
        /// </summary>
        public const string StringCity = "StringCity";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: نام کارخانه
        /// </summary>
        public const string StringFactoryName = "StringFactoryName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: زمان ثبت
        /// </summary>
        public const string StringInsertDateTime = "StringInsertDateTime";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: نوع بسته بندی
        /// </summary>
        public const string StringPackageType = "StringPackageType";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: نام کالا
        /// </summary>
        public const string StringProductName = "StringProductName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: نوع کالا
        /// </summary>
        public const string StringProductType = "StringProductType";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: استان تخلیه
        /// </summary>
        public const string StringProvince = "StringProvince";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تناژ
        /// </summary>
        public const string StringTonnage = "StringTonnage";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تناژ
        /// </summary>
        public const string Tonnage = "Tonnage";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: روستای تخلیه
        /// </summary>
        public const string Village = "Village";
    }
}
