//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.Model.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class City {
        
        /// <summary>
        ///   Looks up a localized string similar to: کد شهر
        /// </summary>
        public static string Code([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.City.Code;
            }
            return global::Resources.Model.City.ResourceManager.GetString("Code", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: نام شهر
        /// </summary>
        public static string Name([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.City.Name;
            }
            return global::Resources.Model.City.ResourceManager.GetString("Name", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: نام استان
        /// </summary>
        public static string Province([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.City.Province;
            }
            return global::Resources.Model.City.ResourceManager.GetString("Province", resourceCulture);
        }
    }
}
namespace Resources.Model.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class CityKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: کد شهر
        /// </summary>
        public const string Code = "Code";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: نام شهر
        /// </summary>
        public const string Name = "Name";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: نام استان
        /// </summary>
        public const string Province = "Province";
    }
}
