//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CurrencyUnit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CurrencyUnit() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Model.CurrencyUnit", typeof(CurrencyUnit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درهم امارات.
        /// </summary>
        public static string AED {
            get {
                return ResourceManager.GetString("AED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ابطال.
        /// </summary>
        public static string CancellationDateTime {
            get {
                return ResourceManager.GetString("CancellationDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ارز.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دلار.
        /// </summary>
        public static string Dollar {
            get {
                return ResourceManager.GetString("Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارزهای.
        /// </summary>
        public static string EnitiesNameOf {
            get {
                return ResourceManager.GetString("EnitiesNameOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارزها.
        /// </summary>
        public static string EntitiesName {
            get {
                return ResourceManager.GetString("EntitiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارز.
        /// </summary>
        public static string EntityName {
            get {
                return ResourceManager.GetString("EntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارز.
        /// </summary>
        public static string EntityNameOf {
            get {
                return ResourceManager.GetString("EntityNameOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یورو.
        /// </summary>
        public static string Euro {
            get {
                return ResourceManager.GetString("Euro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ اعتبار.
        /// </summary>
        public static string ExpireDateTime {
            get {
                return ResourceManager.GetString("ExpireDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پوند انگلیس.
        /// </summary>
        public static string GBP {
            get {
                return ResourceManager.GetString("GBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت.
        /// </summary>
        public static string InsertDateTime {
            get {
                return ResourceManager.GetString("InsertDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیر ترکیه.
        /// </summary>
        public static string LearTurkey {
            get {
                return ResourceManager.GetString("LearTurkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام ارز.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ریال عمان.
        /// </summary>
        public static string OmaniRails {
            get {
                return ResourceManager.GetString("OmaniRails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ریال.
        /// </summary>
        public static string Rails {
            get {
                return ResourceManager.GetString("Rails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارزش ریالی.
        /// </summary>
        public static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روبل.
        /// </summary>
        public static string Ruble {
            get {
                return ResourceManager.GetString("Ruble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روپیه.
        /// </summary>
        public static string Rupee {
            get {
                return ResourceManager.GetString("Rupee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ریال سعودی.
        /// </summary>
        public static string SaudiRails {
            get {
                return ResourceManager.GetString("SaudiRails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرانک سویس.
        /// </summary>
        public static string SwissFranc {
            get {
                return ResourceManager.GetString("SwissFranc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ین.
        /// </summary>
        public static string Yen {
            get {
                return ResourceManager.GetString("Yen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یوان.
        /// </summary>
        public static string Yuan {
            get {
                return ResourceManager.GetString("Yuan", resourceCulture);
            }
        }
    }
}
