//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.Model.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class HeadOfFactor {
        
        /// <summary>
        ///   Looks up a localized string similar to: شماره همراه
        /// </summary>
        public static string CellPhoneNumber([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.HeadOfFactor.CellPhoneNumber;
            }
            return global::Resources.Model.HeadOfFactor.ResourceManager.GetString("CellPhoneNumber", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: شهر
        /// </summary>
        public static string City([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.HeadOfFactor.City;
            }
            return global::Resources.Model.HeadOfFactor.ResourceManager.GetString("City", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: نام شرکت
        /// </summary>
        public static string CompanyName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.HeadOfFactor.CompanyName;
            }
            return global::Resources.Model.HeadOfFactor.ResourceManager.GetString("CompanyName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: شناسه ملی شرکت
        /// </summary>
        public static string CompanyNationalCode([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.HeadOfFactor.CompanyNationalCode;
            }
            return global::Resources.Model.HeadOfFactor.ResourceManager.GetString("CompanyNationalCode", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: توضیحات
        /// </summary>
        public static string Description([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.HeadOfFactor.Description;
            }
            return global::Resources.Model.HeadOfFactor.ResourceManager.GetString("Description", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تا تاریخ
        /// </summary>
        public static string EndDate([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.HeadOfFactor.EndDate;
            }
            return global::Resources.Model.HeadOfFactor.ResourceManager.GetString("EndDate", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: فاکتورها
        /// </summary>
        public static string EnitiesNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.HeadOfFactor.EnitiesNameOf;
            }
            return global::Resources.Model.HeadOfFactor.ResourceManager.GetString("EnitiesNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: فاکتورها
        /// </summary>
        public static string EntitiesName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.HeadOfFactor.EntitiesName;
            }
            return global::Resources.Model.HeadOfFactor.ResourceManager.GetString("EntitiesName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: فاکتور
        /// </summary>
        public static string EntityName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.HeadOfFactor.EntityName;
            }
            return global::Resources.Model.HeadOfFactor.ResourceManager.GetString("EntityName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: فاکتور
        /// </summary>
        public static string EntityNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.HeadOfFactor.EntityNameOf;
            }
            return global::Resources.Model.HeadOfFactor.ResourceManager.GetString("EntityNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تایید نهایی
        /// </summary>
        public static string FinalApprove([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.HeadOfFactor.FinalApprove;
            }
            return global::Resources.Model.HeadOfFactor.ResourceManager.GetString("FinalApprove", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: سرفصل
        /// </summary>
        public static string HeadLine([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.HeadOfFactor.HeadLine;
            }
            return global::Resources.Model.HeadOfFactor.ResourceManager.GetString("HeadLine", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تاریخ ثبت
        /// </summary>
        public static string InsertDateTime([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.HeadOfFactor.InsertDateTime;
            }
            return global::Resources.Model.HeadOfFactor.ResourceManager.GetString("InsertDateTime", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تاریخ فاکتور
        /// </summary>
        public static string InvoiceDate([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.HeadOfFactor.InvoiceDate;
            }
            return global::Resources.Model.HeadOfFactor.ResourceManager.GetString("InvoiceDate", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: شماره فاکتور
        /// </summary>
        public static string InvoiceNumber([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.HeadOfFactor.InvoiceNumber;
            }
            return global::Resources.Model.HeadOfFactor.ResourceManager.GetString("InvoiceNumber", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: پیام ها
        /// </summary>
        public static string Messages([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.HeadOfFactor.Messages;
            }
            return global::Resources.Model.HeadOfFactor.ResourceManager.GetString("Messages", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: استان
        /// </summary>
        public static string Province([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.HeadOfFactor.Province;
            }
            return global::Resources.Model.HeadOfFactor.ResourceManager.GetString("Province", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: درخواست
        /// </summary>
        public static string Request([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.HeadOfFactor.Request;
            }
            return global::Resources.Model.HeadOfFactor.ResourceManager.GetString("Request", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تعرفه خدمت
        /// </summary>
        public static string ServiceTariff([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.HeadOfFactor.ServiceTariff;
            }
            return global::Resources.Model.HeadOfFactor.ResourceManager.GetString("ServiceTariff", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: از تاریخ
        /// </summary>
        public static string StartDate([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.HeadOfFactor.StartDate;
            }
            return global::Resources.Model.HeadOfFactor.ResourceManager.GetString("StartDate", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: زیرفصل
        /// </summary>
        public static string SubHeadLine([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.HeadOfFactor.SubHeadLine;
            }
            return global::Resources.Model.HeadOfFactor.ResourceManager.GetString("SubHeadLine", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: زیرسیستم
        /// </summary>
        public static string SubSystem([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.HeadOfFactor.SubSystem;
            }
            return global::Resources.Model.HeadOfFactor.ResourceManager.GetString("SubSystem", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: پیام به کاربر
        /// </summary>
        public static string SystemMessage([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.HeadOfFactor.SystemMessage;
            }
            return global::Resources.Model.HeadOfFactor.ResourceManager.GetString("SystemMessage", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تاریخ ویرایش
        /// </summary>
        public static string UpdateDateTime([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.HeadOfFactor.UpdateDateTime;
            }
            return global::Resources.Model.HeadOfFactor.ResourceManager.GetString("UpdateDateTime", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: کاربر
        /// </summary>
        public static string User([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.HeadOfFactor.User;
            }
            return global::Resources.Model.HeadOfFactor.ResourceManager.GetString("User", resourceCulture);
        }
    }
}
namespace Resources.Model.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class HeadOfFactorKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: شماره همراه
        /// </summary>
        public const string CellPhoneNumber = "CellPhoneNumber";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: شهر
        /// </summary>
        public const string City = "City";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: نام شرکت
        /// </summary>
        public const string CompanyName = "CompanyName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: شناسه ملی شرکت
        /// </summary>
        public const string CompanyNationalCode = "CompanyNationalCode";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: توضیحات
        /// </summary>
        public const string Description = "Description";

        /// <summary>
        ///   Provides access to string resource key of value similar to: نوع ارز
        /// </summary>
        public const string CurrencyUnit = "CurrencyUnit";

        /// <summary>
        ///   Provides access to string resource key of value similar to: تا تاریخ
        /// </summary>
        public const string EndDate = "EndDate";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: فاکتورها
        /// </summary>
        public const string EnitiesNameOf = "EnitiesNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: فاکتورها
        /// </summary>
        public const string EntitiesName = "EntitiesName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: فاکتور
        /// </summary>
        public const string EntityName = "EntityName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: فاکتور
        /// </summary>
        public const string EntityNameOf = "EntityNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تایید نهایی
        /// </summary>
        public const string FinalApprove = "FinalApprove";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: سرفصل
        /// </summary>
        public const string HeadLine = "HeadLine";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تاریخ ثبت
        /// </summary>
        public const string InsertDateTime = "InsertDateTime";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تاریخ فاکتور
        /// </summary>
        public const string InvoiceDate = "InvoiceDate";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: شماره فاکتور
        /// </summary>
        public const string InvoiceNumber = "InvoiceNumber";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: پیام ها
        /// </summary>
        public const string Messages = "Messages";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: استان
        /// </summary>
        public const string Province = "Province";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: درخواست
        /// </summary>
        public const string Request = "Request";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تعرفه خدمت
        /// </summary>
        public const string ServiceTariff = "ServiceTariff";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: از تاریخ
        /// </summary>
        public const string StartDate = "StartDate";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: زیرفصل
        /// </summary>
        public const string SubHeadLine = "SubHeadLine";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: زیرسیستم
        /// </summary>
        public const string SubSystem = "SubSystem";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: پیام به کاربر
        /// </summary>
        public const string SystemMessage = "SystemMessage";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تاریخ ویرایش
        /// </summary>
        public const string UpdateDateTime = "UpdateDateTime";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: کاربر
        /// </summary>
        public const string User = "User";
    }
}
