//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.Model.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Payment {
        
        /// <summary>
        ///   Looks up a localized string similar to: مبلغ پرداختی
        /// </summary>
        public static string AmountPaid([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Payment.AmountPaid;
            }
            return global::Resources.Model.Payment.ResourceManager.GetString("AmountPaid", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: پست الکترونیک
        /// </summary>
        public static string Email([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Payment.Email;
            }
            return global::Resources.Model.Payment.ResourceManager.GetString("Email", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: پرداخت های
        /// </summary>
        public static string EnitiesNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Payment.EnitiesNameOf;
            }
            return global::Resources.Model.Payment.ResourceManager.GetString("EnitiesNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: پرداخت ها
        /// </summary>
        public static string EntitiesName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Payment.EntitiesName;
            }
            return global::Resources.Model.Payment.ResourceManager.GetString("EntitiesName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: پرداخت
        /// </summary>
        public static string EntityName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Payment.EntityName;
            }
            return global::Resources.Model.Payment.ResourceManager.GetString("EntityName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: پرداخت
        /// </summary>
        public static string EntityNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Payment.EntityNameOf;
            }
            return global::Resources.Model.Payment.ResourceManager.GetString("EntityNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: شماره ارجاع
        /// </summary>
        public static string ReferenceNumber([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Payment.ReferenceNumber;
            }
            return global::Resources.Model.Payment.ResourceManager.GetString("ReferenceNumber", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: درخواست
        /// </summary>
        public static string Request([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Payment.Request;
            }
            return global::Resources.Model.Payment.ResourceManager.GetString("Request", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تاریخ انجام تراکنش
        /// </summary>
        public static string TransactionDate([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Payment.TransactionDate;
            }
            return global::Resources.Model.Payment.ResourceManager.GetString("TransactionDate", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: نتیجه انجام تراکنش
        /// </summary>
        public static string TransactionResults([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Payment.TransactionResults;
            }
            return global::Resources.Model.Payment.ResourceManager.GetString("TransactionResults", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: آی پی سیستم
        /// </summary>
        public static string UserIPAddress([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Payment.UserIPAddress;
            }
            return global::Resources.Model.Payment.ResourceManager.GetString("UserIPAddress", resourceCulture);
        }
    }
}
namespace Resources.Model.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class PaymentKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: مبلغ پرداختی
        /// </summary>
        public const string AmountPaid = "AmountPaid";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: پست الکترونیک
        /// </summary>
        public const string Email = "Email";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: پرداخت های
        /// </summary>
        public const string EnitiesNameOf = "EnitiesNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: پرداخت ها
        /// </summary>
        public const string EntitiesName = "EntitiesName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: پرداخت
        /// </summary>
        public const string EntityName = "EntityName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: پرداخت
        /// </summary>
        public const string EntityNameOf = "EntityNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: شماره ارجاع
        /// </summary>
        public const string ReferenceNumber = "ReferenceNumber";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: درخواست
        /// </summary>
        public const string Request = "Request";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تاریخ انجام تراکنش
        /// </summary>
        public const string TransactionDate = "TransactionDate";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: نتیجه انجام تراکنش
        /// </summary>
        public const string TransactionResults = "TransactionResults";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: آی پی سیستم
        /// </summary>
        public const string UserIPAddress = "UserIPAddress";
    }
}
