//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.Model.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Request {
        
        /// <summary>
        ///   Looks up a localized string similar to: مبلغ پرداخت
        /// </summary>
        public static string AmountPaid([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.AmountPaid;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("AmountPaid", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تاریخ پرداخت
        /// </summary>
        public static string AmountPaidDate([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.AmountPaidDate;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("AmountPaidDate", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: کد 17 رقمی بانک
        /// </summary>
        public static string BankDigitCode([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.BankDigitCode;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("BankDigitCode", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: میزان کل ارز
        /// </summary>
        public static string BaseCurrencyValue([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.BaseCurrencyValue;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("BaseCurrencyValue", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: شماره همراه
        /// </summary>
        public static string CellPhoneNumber([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.CellPhoneNumber;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("CellPhoneNumber", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: شهر
        /// </summary>
        public static string City([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.City;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("City", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: نوع کالا
        /// </summary>
        public static string CommodityType([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.CommodityType;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("CommodityType", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: واحد کالا
        /// </summary>
        public static string CommodityUnit([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.CommodityUnit;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("CommodityUnit", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: نام شرکت
        /// </summary>
        public static string CompanyName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.CompanyName;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("CompanyName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: شناسه ملی شرکت
        /// </summary>
        public static string CompanyNationalCode([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.CompanyNationalCode;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("CompanyNationalCode", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: کد ارز
        /// </summary>
        public static string CurrencyCode([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.CurrencyCode;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("CurrencyCode", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: ارزش ریالی
        /// </summary>
        public static string CurrencyRation([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.CurrencyRation;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("CurrencyRation", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: نوع ارز
        /// </summary>
        public static string CurrencyUnit([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.CurrencyUnit;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("CurrencyUnit", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: میزان ارز پرداختی شرکت
        /// </summary>
        public static string CurrencyValue([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.CurrencyValue;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("CurrencyValue", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: شناسه واریز
        /// </summary>
        public static string DepositNumber([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.DepositNumber;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("DepositNumber", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: توضیحات
        /// </summary>
        public static string Description([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.Description;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("Description", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تا تاریخ صدور
        /// </summary>
        public static string EndDate([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.EndDate;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("EndDate", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: درخواست های
        /// </summary>
        public static string EnitiesNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.EnitiesNameOf;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("EnitiesNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: درخواست ها
        /// </summary>
        public static string EntitiesName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.EntitiesName;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("EntitiesName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: درخواست
        /// </summary>
        public static string EntityName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.EntityName;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("EntityName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: درخواست
        /// </summary>
        public static string EntityNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.EntityNameOf;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("EntityNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: فایل ها
        /// </summary>
        public static string FileStream([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.FileStream;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("FileStream", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: از مبلغ
        /// </summary>
        public static string FromAmount([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.FromAmount;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("FromAmount", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: شماره درخواست ثبت سفارش
        /// </summary>
        public static string ImportRecordNumber([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.ImportRecordNumber;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("ImportRecordNumber", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: شماره درخواست(فوب)
        /// </summary>
        public static string ImportRecordNumber2([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.ImportRecordNumber2;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("ImportRecordNumber2", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تاریخ فاکتور
        /// </summary>
        public static string InvoiceDate([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.InvoiceDate;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("InvoiceDate", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: شماره فاکتور
        /// </summary>
        public static string InvoiceNumber([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.InvoiceNumber;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("InvoiceNumber", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تاریخ مجوز
        /// </summary>
        public static string LicenseDate([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.LicenseDate;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("LicenseDate", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: شماره مجوز
        /// </summary>
        public static string LisenceNumber([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.LisenceNumber;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("LisenceNumber", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: پیام ها
        /// </summary>
        public static string Messages([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.Messages;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("Messages", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: دفاتر
        /// </summary>
        public static string Office([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.Office;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("Office", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: خدمات دفتر
        /// </summary>
        public static string OfficeService([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.OfficeService;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("OfficeService", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: کد 13 رقمی سازمان
        /// </summary>
        public static string OrganDigitCode([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.OrganDigitCode;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("OrganDigitCode", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تا تاریخ پرداخت
        /// </summary>
        public static string PayEndDate([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.PayEndDate;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("PayEndDate", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: از تاریخ پرداخت
        /// </summary>
        public static string PayStartDate([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.PayStartDate;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("PayStartDate", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: پرداخت ها
        /// </summary>
        public static string Payments([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.Payments;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("Payments", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تاریخ پرفورما
        /// </summary>
        public static string PerformDate([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.PerformDate;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("PerformDate", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: شماره پرفورما
        /// </summary>
        public static string PerformNumber([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.PerformNumber;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("PerformNumber", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: فایل پیش فاکتور
        /// </summary>
        public static string PerformStreem([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.PerformStreem;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("PerformStreem", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: استان
        /// </summary>
        public static string Province([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.Province;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("Province", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تاریخ درخواست
        /// </summary>
        public static string RecordDate([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.RecordDate;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("RecordDate", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: شماره درخواست (شماره فیش سیستم مبدا)
        /// </summary>
        public static string RecordNumber([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.RecordNumber;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("RecordNumber", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: شماره حواله
        /// </summary>
        public static string RemittanceNumber([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.RemittanceNumber;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("RemittanceNumber", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: وضعیت درخواست
        /// </summary>
        public static string RequestState([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.RequestState;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("RequestState", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تاریخ مجوز
        /// </summary>
        public static string SecDate([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.SecDate;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("SecDate", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: شماره مجوز
        /// </summary>
        public static string SecNumber([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.SecNumber;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("SecNumber", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تعرفه خدمت
        /// </summary>
        public static string ServiceTariff([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.ServiceTariff;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("ServiceTariff", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: از تاریخ صدور
        /// </summary>
        public static string StartDate([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.StartDate;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("StartDate", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: زیرسیستم
        /// </summary>
        public static string SubSystem([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.SubSystem;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("SubSystem", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: پیام به کاربر
        /// </summary>
        public static string SystemMessage([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.SystemMessage;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("SystemMessage", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تعرفه کنونی سیستم پرداخت
        /// </summary>
        public static string SystemTarefeh([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.SystemTarefeh;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("SystemTarefeh", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تعرفه اعلامی از سرویس
        /// </summary>
        public static string Tarefeh([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.Tarefeh;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("Tarefeh", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تا مبلغ
        /// </summary>
        public static string ToAmount([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.ToAmount;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("ToAmount", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: میزان کالا
        /// </summary>
        public static string TotalValue([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.TotalValue;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("TotalValue", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: کاربر
        /// </summary>
        public static string User([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.User;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("User", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: فایل مجوز
        /// </summary>
        public static string VIPStreem([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.VIPStreem;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("VIPStreem", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: کد مجازی سیستم
        /// </summary>
        public static string VirtualCode([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Request.VirtualCode;
            }
            return global::Resources.Model.Request.ResourceManager.GetString("VirtualCode", resourceCulture);
        }
        
        /// <summary>
        ///   Provides access to string resources.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public class Bank {
            
            /// <summary>
            ///   Looks up a localized string similar to: کد وضعیت
            /// </summary>
            public static string AppStatus([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
                if (object.ReferenceEquals(resourceCulture, null)) {
                    return global::Resources.Model.Request.Bank_AppStatus;
                }
                return global::Resources.Model.Request.ResourceManager.GetString("Bank_AppStatus", resourceCulture);
            }
            
            /// <summary>
            ///   Looks up a localized string similar to: کد پاسخ
            /// </summary>
            public static string AppStatusCode([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
                if (object.ReferenceEquals(resourceCulture, null)) {
                    return global::Resources.Model.Request.Bank_AppStatusCode;
                }
                return global::Resources.Model.Request.ResourceManager.GetString("Bank_AppStatusCode", resourceCulture);
            }
            
            /// <summary>
            ///   Looks up a localized string similar to: شرح وضعیت
            /// </summary>
            public static string AppStatusDescription([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
                if (object.ReferenceEquals(resourceCulture, null)) {
                    return global::Resources.Model.Request.Bank_AppStatusDescription;
                }
                return global::Resources.Model.Request.ResourceManager.GetString("Bank_AppStatusDescription", resourceCulture);
            }
            
            /// <summary>
            ///   Looks up a localized string similar to: شماره مرجع
            /// </summary>
            public static string BankReciptNumber([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
                if (object.ReferenceEquals(resourceCulture, null)) {
                    return global::Resources.Model.Request.Bank_BankReciptNumber;
                }
                return global::Resources.Model.Request.ResourceManager.GetString("Bank_BankReciptNumber", resourceCulture);
            }
            
            /// <summary>
            ///   Looks up a localized string similar to: شماره حساب مشتری
            /// </summary>
            public static string CardHolderAccNumber([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
                if (object.ReferenceEquals(resourceCulture, null)) {
                    return global::Resources.Model.Request.Bank_CardHolderAccNumber;
                }
                return global::Resources.Model.Request.ResourceManager.GetString("Bank_CardHolderAccNumber", resourceCulture);
            }
            
            /// <summary>
            ///   Looks up a localized string similar to: نام دارنده کارت
            /// </summary>
            public static string CardHolderName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
                if (object.ReferenceEquals(resourceCulture, null)) {
                    return global::Resources.Model.Request.Bank_CardHolderName;
                }
                return global::Resources.Model.Request.ResourceManager.GetString("Bank_CardHolderName", resourceCulture);
            }
            
            /// <summary>
            ///   Looks up a localized string similar to: شماره کارت مشتری
            /// </summary>
            public static string CustomerCardNumber([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
                if (object.ReferenceEquals(resourceCulture, null)) {
                    return global::Resources.Model.Request.Bank_CustomerCardNumber;
                }
                return global::Resources.Model.Request.ResourceManager.GetString("Bank_CustomerCardNumber", resourceCulture);
            }
            
            /// <summary>
            ///   Looks up a localized string similar to: کد خطا
            /// </summary>
            public static string FailCode([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
                if (object.ReferenceEquals(resourceCulture, null)) {
                    return global::Resources.Model.Request.Bank_FailCode;
                }
                return global::Resources.Model.Request.ResourceManager.GetString("Bank_FailCode", resourceCulture);
            }
            
            /// <summary>
            ///   Looks up a localized string similar to: شماره پذیرنده
            /// </summary>
            public static string MerchantId([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
                if (object.ReferenceEquals(resourceCulture, null)) {
                    return global::Resources.Model.Request.Bank_MerchantId;
                }
                return global::Resources.Model.Request.ResourceManager.GetString("Bank_MerchantId", resourceCulture);
            }
            
            /// <summary>
            ///   Looks up a localized string similar to: -----
            /// </summary>
            public static string NewlyCommitted([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
                if (object.ReferenceEquals(resourceCulture, null)) {
                    return global::Resources.Model.Request.Bank_NewlyCommitted;
                }
                return global::Resources.Model.Request.ResourceManager.GetString("Bank_NewlyCommitted", resourceCulture);
            }
            
            /// <summary>
            ///   Looks up a localized string similar to: تاریخ میلادی
            /// </summary>
            public static string RealTransactionDateTime([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
                if (object.ReferenceEquals(resourceCulture, null)) {
                    return global::Resources.Model.Request.Bank_RealTransactionDateTime;
                }
                return global::Resources.Model.Request.ResourceManager.GetString("Bank_RealTransactionDateTime", resourceCulture);
            }
            
            /// <summary>
            ///   Looks up a localized string similar to: کد شعبه
            /// </summary>
            public static string RefrenceNumber([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
                if (object.ReferenceEquals(resourceCulture, null)) {
                    return global::Resources.Model.Request.Bank_RefrenceNumber;
                }
                return global::Resources.Model.Request.ResourceManager.GetString("Bank_RefrenceNumber", resourceCulture);
            }
            
            /// <summary>
            ///   Looks up a localized string similar to: کد اولیه پرداخت
            /// </summary>
            public static string RequestKey([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
                if (object.ReferenceEquals(resourceCulture, null)) {
                    return global::Resources.Model.Request.Bank_RequestKey;
                }
                return global::Resources.Model.Request.ResourceManager.GetString("Bank_RequestKey", resourceCulture);
            }
            
            /// <summary>
            ///   Looks up a localized string similar to: کد پاسخ
            /// </summary>
            public static string ResponseCode([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
                if (object.ReferenceEquals(resourceCulture, null)) {
                    return global::Resources.Model.Request.Bank_ResponseCode;
                }
                return global::Resources.Model.Request.ResourceManager.GetString("Bank_ResponseCode", resourceCulture);
            }
            
            /// <summary>
            ///   Looks up a localized string similar to: تاریخ پرداخت
            /// </summary>
            public static string ShamsiDate([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
                if (object.ReferenceEquals(resourceCulture, null)) {
                    return global::Resources.Model.Request.Bank_ShamsiDate;
                }
                return global::Resources.Model.Request.ResourceManager.GetString("Bank_ShamsiDate", resourceCulture);
            }
            
            /// <summary>
            ///   Looks up a localized string similar to: شماره ترمينال
            /// </summary>
            public static string Terminal([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
                if (object.ReferenceEquals(resourceCulture, null)) {
                    return global::Resources.Model.Request.Bank_Terminal;
                }
                return global::Resources.Model.Request.ResourceManager.GetString("Bank_Terminal", resourceCulture);
            }
            
            /// <summary>
            ///   Looks up a localized string similar to: شماره پیگیری بانکی
            /// </summary>
            public static string TraceNo([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
                if (object.ReferenceEquals(resourceCulture, null)) {
                    return global::Resources.Model.Request.Bank_TraceNo;
                }
                return global::Resources.Model.Request.ResourceManager.GetString("Bank_TraceNo", resourceCulture);
            }
        }
    }
}
namespace Resources.Model.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class RequestKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: مبلغ پرداخت
        /// </summary>
        public const string AmountPaid = "AmountPaid";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تاریخ پرداخت
        /// </summary>
        public const string AmountPaidDate = "AmountPaidDate";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: کد 17 رقمی بانک
        /// </summary>
        public const string BankDigitCode = "BankDigitCode";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: میزان کل ارز
        /// </summary>
        public const string BaseCurrencyValue = "BaseCurrencyValue";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: شماره همراه
        /// </summary>
        public const string CellPhoneNumber = "CellPhoneNumber";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: شهر
        /// </summary>
        public const string City = "City";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: نوع کالا
        /// </summary>
        public const string CommodityType = "CommodityType";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: واحد کالا
        /// </summary>
        public const string CommodityUnit = "CommodityUnit";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: نام شرکت
        /// </summary>
        public const string CompanyName = "CompanyName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: شناسه ملی شرکت
        /// </summary>
        public const string CompanyNationalCode = "CompanyNationalCode";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: کد ارز
        /// </summary>
        public const string CurrencyCode = "CurrencyCode";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: ارزش ریالی
        /// </summary>
        public const string CurrencyRation = "CurrencyRation";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: نوع ارز
        /// </summary>
        public const string CurrencyUnit = "CurrencyUnit";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: میزان ارز پرداختی شرکت
        /// </summary>
        public const string CurrencyValue = "CurrencyValue";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: شناسه واریز
        /// </summary>
        public const string DepositNumber = "DepositNumber";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: توضیحات
        /// </summary>
        public const string Description = "Description";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تا تاریخ صدور
        /// </summary>
        public const string EndDate = "EndDate";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: درخواست های
        /// </summary>
        public const string EnitiesNameOf = "EnitiesNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: درخواست ها
        /// </summary>
        public const string EntitiesName = "EntitiesName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: درخواست
        /// </summary>
        public const string EntityName = "EntityName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: درخواست
        /// </summary>
        public const string EntityNameOf = "EntityNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: فایل ها
        /// </summary>
        public const string FileStream = "FileStream";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: از مبلغ
        /// </summary>
        public const string FromAmount = "FromAmount";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: شماره درخواست ثبت سفارش
        /// </summary>
        public const string ImportRecordNumber = "ImportRecordNumber";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: شماره درخواست(فوب)
        /// </summary>
        public const string ImportRecordNumber2 = "ImportRecordNumber2";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تاریخ فاکتور
        /// </summary>
        public const string InvoiceDate = "InvoiceDate";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: شماره فاکتور
        /// </summary>
        public const string InvoiceNumber = "InvoiceNumber";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تاریخ مجوز
        /// </summary>
        public const string LicenseDate = "LicenseDate";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: شماره مجوز
        /// </summary>
        public const string LisenceNumber = "LisenceNumber";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: پیام ها
        /// </summary>
        public const string Messages = "Messages";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: دفاتر
        /// </summary>
        public const string Office = "Office";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: خدمات دفتر
        /// </summary>
        public const string OfficeService = "OfficeService";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: کد 13 رقمی سازمان
        /// </summary>
        public const string OrganDigitCode = "OrganDigitCode";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تا تاریخ پرداخت
        /// </summary>
        public const string PayEndDate = "PayEndDate";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: از تاریخ پرداخت
        /// </summary>
        public const string PayStartDate = "PayStartDate";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: پرداخت ها
        /// </summary>
        public const string Payments = "Payments";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تاریخ پرفورما
        /// </summary>
        public const string PerformDate = "PerformDate";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: شماره پرفورما
        /// </summary>
        public const string PerformNumber = "PerformNumber";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: فایل پیش فاکتور
        /// </summary>
        public const string PerformStreem = "PerformStreem";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: استان
        /// </summary>
        public const string Province = "Province";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تاریخ درخواست
        /// </summary>
        public const string RecordDate = "RecordDate";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: شماره درخواست (شماره فیش سیستم مبدا)
        /// </summary>
        public const string RecordNumber = "RecordNumber";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: شماره حواله
        /// </summary>
        public const string RemittanceNumber = "RemittanceNumber";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: وضعیت درخواست
        /// </summary>
        public const string RequestState = "RequestState";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تاریخ مجوز
        /// </summary>
        public const string SecDate = "SecDate";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: شماره مجوز
        /// </summary>
        public const string SecNumber = "SecNumber";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تعرفه خدمت
        /// </summary>
        public const string ServiceTariff = "ServiceTariff";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: از تاریخ صدور
        /// </summary>
        public const string StartDate = "StartDate";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: زیرسیستم
        /// </summary>
        public const string SubSystem = "SubSystem";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: پیام به کاربر
        /// </summary>
        public const string SystemMessage = "SystemMessage";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تعرفه کنونی سیستم پرداخت
        /// </summary>
        public const string SystemTarefeh = "SystemTarefeh";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تعرفه اعلامی از سرویس
        /// </summary>
        public const string Tarefeh = "Tarefeh";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تا مبلغ
        /// </summary>
        public const string ToAmount = "ToAmount";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: میزان کالا
        /// </summary>
        public const string TotalValue = "TotalValue";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: کاربر
        /// </summary>
        public const string User = "User";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: فایل مجوز
        /// </summary>
        public const string VIPStreem = "VIPStreem";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: کد مجازی سیستم
        /// </summary>
        public const string VirtualCode = "VirtualCode";
        
        /// <summary>
        ///   Provides access to string resource keys.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public class Bank {
            
            /// <summary>
            ///   Provides access to string resource key of value similar to: کد وضعیت
            /// </summary>
            public const string AppStatus = "Bank_AppStatus";
            
            /// <summary>
            ///   Provides access to string resource key of value similar to: کد پاسخ
            /// </summary>
            public const string AppStatusCode = "Bank_AppStatusCode";
            
            /// <summary>
            ///   Provides access to string resource key of value similar to: شرح وضعیت
            /// </summary>
            public const string AppStatusDescription = "Bank_AppStatusDescription";
            
            /// <summary>
            ///   Provides access to string resource key of value similar to: شماره مرجع
            /// </summary>
            public const string BankReciptNumber = "Bank_BankReciptNumber";
            
            /// <summary>
            ///   Provides access to string resource key of value similar to: شماره حساب مشتری
            /// </summary>
            public const string CardHolderAccNumber = "Bank_CardHolderAccNumber";
            
            /// <summary>
            ///   Provides access to string resource key of value similar to: نام دارنده کارت
            /// </summary>
            public const string CardHolderName = "Bank_CardHolderName";
            
            /// <summary>
            ///   Provides access to string resource key of value similar to: شماره کارت مشتری
            /// </summary>
            public const string CustomerCardNumber = "Bank_CustomerCardNumber";
            
            /// <summary>
            ///   Provides access to string resource key of value similar to: کد خطا
            /// </summary>
            public const string FailCode = "Bank_FailCode";
            
            /// <summary>
            ///   Provides access to string resource key of value similar to: شماره پذیرنده
            /// </summary>
            public const string MerchantId = "Bank_MerchantId";
            
            /// <summary>
            ///   Provides access to string resource key of value similar to: -----
            /// </summary>
            public const string NewlyCommitted = "Bank_NewlyCommitted";
            
            /// <summary>
            ///   Provides access to string resource key of value similar to: تاریخ میلادی
            /// </summary>
            public const string RealTransactionDateTime = "Bank_RealTransactionDateTime";
            
            /// <summary>
            ///   Provides access to string resource key of value similar to: کد شعبه
            /// </summary>
            public const string RefrenceNumber = "Bank_RefrenceNumber";
            
            /// <summary>
            ///   Provides access to string resource key of value similar to: کد اولیه پرداخت
            /// </summary>
            public const string RequestKey = "Bank_RequestKey";
            
            /// <summary>
            ///   Provides access to string resource key of value similar to: کد پاسخ
            /// </summary>
            public const string ResponseCode = "Bank_ResponseCode";
            
            /// <summary>
            ///   Provides access to string resource key of value similar to: تاریخ پرداخت
            /// </summary>
            public const string ShamsiDate = "Bank_ShamsiDate";
            
            /// <summary>
            ///   Provides access to string resource key of value similar to: شماره ترمينال
            /// </summary>
            public const string Terminal = "Bank_Terminal";
            
            /// <summary>
            ///   Provides access to string resource key of value similar to: شماره پیگیری بانکی
            /// </summary>
            public const string TraceNo = "Bank_TraceNo";
        }
    }
}
