//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.Model.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ServiceTariff {
        
        /// <summary>
        ///   Looks up a localized string similar to: تعرفه به ریال
        /// </summary>
        public static string Amount([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.ServiceTariff.Amount;
            }
            return global::Resources.Model.ServiceTariff.ResourceManager.GetString("Amount", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: عنوان حساب
        /// </summary>
        public static string BankAccount([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.ServiceTariff.BankAccount;
            }
            return global::Resources.Model.ServiceTariff.ResourceManager.GetString("BankAccount", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تعرفه خدمات
        /// </summary>
        public static string EnitiesNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.ServiceTariff.EnitiesNameOf;
            }
            return global::Resources.Model.ServiceTariff.ResourceManager.GetString("EnitiesNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تعرفه خدمات
        /// </summary>
        public static string EntitiesName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.ServiceTariff.EntitiesName;
            }
            return global::Resources.Model.ServiceTariff.ResourceManager.GetString("EntitiesName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تعرفه خدمت
        /// </summary>
        public static string EntityName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.ServiceTariff.EntityName;
            }
            return global::Resources.Model.ServiceTariff.ResourceManager.GetString("EntityName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تعرفه خدمت
        /// </summary>
        public static string EntityNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.ServiceTariff.EntityNameOf;
            }
            return global::Resources.Model.ServiceTariff.ResourceManager.GetString("EntityNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تاریخ ثبت
        /// </summary>
        public static string InsertDateTime([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.ServiceTariff.InsertDateTime;
            }
            return global::Resources.Model.ServiceTariff.ResourceManager.GetString("InsertDateTime", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: عنوان
        /// </summary>
        public static string Name([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.ServiceTariff.Name;
            }
            return global::Resources.Model.ServiceTariff.ResourceManager.GetString("Name", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: کد اصلی
        /// </summary>
        public static string RCode([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.ServiceTariff.RCode;
            }
            return global::Resources.Model.ServiceTariff.ResourceManager.GetString("RCode", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: زیر گروه سرفصل تعرفه
        /// </summary>
        public static string SubHeadLine([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.ServiceTariff.SubHeadLine;
            }
            return global::Resources.Model.ServiceTariff.ResourceManager.GetString("SubHeadLine", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: واحد
        /// </summary>
        public static string Unit([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.ServiceTariff.Unit;
            }
            return global::Resources.Model.ServiceTariff.ResourceManager.GetString("Unit", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تاریخ ویرایش
        /// </summary>
        public static string UpdateDateTime([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.ServiceTariff.UpdateDateTime;
            }
            return global::Resources.Model.ServiceTariff.ResourceManager.GetString("UpdateDateTime", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: کد مجازی
        /// </summary>
        public static string VCode([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.ServiceTariff.VCode;
            }
            return global::Resources.Model.ServiceTariff.ResourceManager.GetString("VCode", resourceCulture);
        }
    }
}
namespace Resources.Model.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ServiceTariffKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تعرفه به ریال
        /// </summary>
        public const string Amount = "Amount";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: عنوان حساب
        /// </summary>
        public const string BankAccount = "BankAccount";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تعرفه خدمات
        /// </summary>
        public const string EnitiesNameOf = "EnitiesNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تعرفه خدمات
        /// </summary>
        public const string EntitiesName = "EntitiesName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تعرفه خدمت
        /// </summary>
        public const string EntityName = "EntityName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تعرفه خدمت
        /// </summary>
        public const string EntityNameOf = "EntityNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تاریخ ثبت
        /// </summary>
        public const string InsertDateTime = "InsertDateTime";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: عنوان
        /// </summary>
        public const string Name = "Name";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: کد اصلی
        /// </summary>
        public const string RCode = "RCode";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: زیر گروه سرفصل تعرفه
        /// </summary>
        public const string SubHeadLine = "SubHeadLine";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: واحد
        /// </summary>
        public const string Unit = "Unit";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تاریخ ویرایش
        /// </summary>
        public const string UpdateDateTime = "UpdateDateTime";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: کد مجازی
        /// </summary>
        public const string VCode = "VCode";
    }
}
