//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.Model.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Unit {
        
        /// <summary>
        ///   Looks up a localized string similar to: توضیحات
        /// </summary>
        public static string Description([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Unit.Description;
            }
            return global::Resources.Model.Unit.ResourceManager.GetString("Description", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: واحدها
        /// </summary>
        public static string EnitiesNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Unit.EnitiesNameOf;
            }
            return global::Resources.Model.Unit.ResourceManager.GetString("EnitiesNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: واحدها
        /// </summary>
        public static string EntitiesName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Unit.EntitiesName;
            }
            return global::Resources.Model.Unit.ResourceManager.GetString("EntitiesName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: واحد
        /// </summary>
        public static string EntityName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Unit.EntityName;
            }
            return global::Resources.Model.Unit.ResourceManager.GetString("EntityName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: واحد
        /// </summary>
        public static string EntityNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Unit.EntityNameOf;
            }
            return global::Resources.Model.Unit.ResourceManager.GetString("EntityNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تاریخ ثبت
        /// </summary>
        public static string InsertDateTime([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Unit.InsertDateTime;
            }
            return global::Resources.Model.Unit.ResourceManager.GetString("InsertDateTime", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: عنوان
        /// </summary>
        public static string Name([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.Unit.Name;
            }
            return global::Resources.Model.Unit.ResourceManager.GetString("Name", resourceCulture);
        }
    }
}
namespace Resources.Model.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class UnitKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: توضیحات
        /// </summary>
        public const string Description = "Description";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: واحدها
        /// </summary>
        public const string EnitiesNameOf = "EnitiesNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: واحدها
        /// </summary>
        public const string EntitiesName = "EntitiesName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: واحد
        /// </summary>
        public const string EntityName = "EntityName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: واحد
        /// </summary>
        public const string EntityNameOf = "EntityNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تاریخ ثبت
        /// </summary>
        public const string InsertDateTime = "InsertDateTime";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: عنوان
        /// </summary>
        public const string Name = "Name";
    }
}
