//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.Model.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class User {
        
        /// <summary>
        ///   Looks up a localized string similar to: آدرس
        /// </summary>
        public static string Address([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.User.Address;
            }
            return global::Resources.Model.User.ResourceManager.GetString("Address", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: احراز هویت
        /// </summary>
        public static string Authenticate([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.User.Authenticate;
            }
            return global::Resources.Model.User.ResourceManager.GetString("Authenticate", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: شماره تماس
        /// </summary>
        public static string BuyerMobile([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.User.BuyerMobile;
            }
            return global::Resources.Model.User.ResourceManager.GetString("BuyerMobile", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: شهر
        /// </summary>
        public static string City([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.User.City;
            }
            return global::Resources.Model.User.ResourceManager.GetString("City", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: کاربر های
        /// </summary>
        public static string EnitiesNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.User.EnitiesNameOf;
            }
            return global::Resources.Model.User.ResourceManager.GetString("EnitiesNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: کاربر ها
        /// </summary>
        public static string EntitiesName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.User.EntitiesName;
            }
            return global::Resources.Model.User.ResourceManager.GetString("EntitiesName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: کاربر
        /// </summary>
        public static string EntityName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.User.EntityName;
            }
            return global::Resources.Model.User.ResourceManager.GetString("EntityName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: کاربر
        /// </summary>
        public static string EntityNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.User.EntityNameOf;
            }
            return global::Resources.Model.User.ResourceManager.GetString("EntityNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: نام و نام خانوادگی
        /// </summary>
        public static string FullName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.User.FullName;
            }
            return global::Resources.Model.User.ResourceManager.GetString("FullName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: فعال
        /// </summary>
        public static string IsActive([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.User.IsActive;
            }
            return global::Resources.Model.User.ResourceManager.GetString("IsActive", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: مجوز تایید پروانه ها
        /// </summary>
        public static string IsApprovallicense([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.User.IsApprovallicense;
            }
            return global::Resources.Model.User.ResourceManager.GetString("IsApprovallicense", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: زمان آخرین ورود
        /// </summary>
        public static string LastLoginDateTime([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.User.LastLoginDateTime;
            }
            return global::Resources.Model.User.ResourceManager.GetString("LastLoginDateTime", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تعداد دفعات ورود به سیستم
        /// </summary>
        public static string LoginCount([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.User.LoginCount;
            }
            return global::Resources.Model.User.ResourceManager.GetString("LoginCount", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: گذرواژه
        /// </summary>
        public static string Password([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.User.Password;
            }
            return global::Resources.Model.User.ResourceManager.GetString("Password", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: استان
        /// </summary>
        public static string Province([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.User.Province;
            }
            return global::Resources.Model.User.ResourceManager.GetString("Province", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: نقش کاربری
        /// </summary>
        public static string Role([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.User.Role;
            }
            return global::Resources.Model.User.ResourceManager.GetString("Role", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: شناسه کاربری
        /// </summary>
        public static string UserName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.User.UserName;
            }
            return global::Resources.Model.User.ResourceManager.GetString("UserName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: مبلغ اعتبار
        /// </summary>
        public static string creditAmount([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Model.User.creditAmount;
            }
            return global::Resources.Model.User.ResourceManager.GetString("creditAmount", resourceCulture);
        }
    }
}
namespace Resources.Model.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class UserKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: آدرس
        /// </summary>
        public const string Address = "Address";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: احراز هویت
        /// </summary>
        public const string Authenticate = "Authenticate";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: شماره تماس
        /// </summary>
        public const string BuyerMobile = "BuyerMobile";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: شهر
        /// </summary>
        public const string City = "City";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: کاربر های
        /// </summary>
        public const string EnitiesNameOf = "EnitiesNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: کاربر ها
        /// </summary>
        public const string EntitiesName = "EntitiesName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: کاربر
        /// </summary>
        public const string EntityName = "EntityName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: کاربر
        /// </summary>
        public const string EntityNameOf = "EntityNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: نام و نام خانوادگی
        /// </summary>
        public const string FullName = "FullName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: فعال
        /// </summary>
        public const string IsActive = "IsActive";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: مجوز تایید پروانه ها
        /// </summary>
        public const string IsApprovallicense = "IsApprovallicense";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: زمان آخرین ورود
        /// </summary>
        public const string LastLoginDateTime = "LastLoginDateTime";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تعداد دفعات ورود به سیستم
        /// </summary>
        public const string LoginCount = "LoginCount";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: گذرواژه
        /// </summary>
        public const string Password = "Password";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: استان
        /// </summary>
        public const string Province = "Province";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: نقش کاربری
        /// </summary>
        public const string Role = "Role";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: شناسه کاربری
        /// </summary>
        public const string UserName = "UserName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: مبلغ اعتبار
        /// </summary>
        public const string creditAmount = "creditAmount";
    }
}
