//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.Enum.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class EnumTypesList {
        
        /// <summary>
        ///   Looks up a localized string similar to: انواع دسترسی
        /// </summary>
        public static string AccessTypes([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.EnumTypesList.AccessTypes;
            }
            return global::Resources.Enum.EnumTypesList.ResourceManager.GetString("AccessTypes", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: انواع واحد ارز
        /// </summary>
        public static string CurrencyUnits([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.EnumTypesList.CurrencyUnits;
            }
            return global::Resources.Enum.EnumTypesList.ResourceManager.GetString("CurrencyUnits", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: انواع ثابت
        /// </summary>
        public static string EnumTypes([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.EnumTypesList.EnumTypes;
            }
            return global::Resources.Enum.EnumTypesList.ResourceManager.GetString("EnumTypes", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: انواع فایل
        /// </summary>
        public static string FileTypes([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.EnumTypesList.FileTypes;
            }
            return global::Resources.Enum.EnumTypesList.ResourceManager.GetString("FileTypes", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: انواع ثبت لاگ سیستم
        /// </summary>
        public static string LogTypes([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.EnumTypesList.LogTypes;
            }
            return global::Resources.Enum.EnumTypesList.ResourceManager.GetString("LogTypes", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: انواع پیام ها
        /// </summary>
        public static string PageMessageTypes([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.EnumTypesList.PageMessageTypes;
            }
            return global::Resources.Enum.EnumTypesList.ResourceManager.GetString("PageMessageTypes", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: انواع وضعیت درخواست
        /// </summary>
        public static string RequestStates([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.EnumTypesList.RequestStates;
            }
            return global::Resources.Enum.EnumTypesList.ResourceManager.GetString("RequestStates", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: انواع درخواست ها
        /// </summary>
        public static string RequestTypes([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.EnumTypesList.RequestTypes;
            }
            return global::Resources.Enum.EnumTypesList.ResourceManager.GetString("RequestTypes", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: انواع نقش ها
        /// </summary>
        public static string Roles([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.EnumTypesList.Roles;
            }
            return global::Resources.Enum.EnumTypesList.ResourceManager.GetString("Roles", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: انواع پاسخ های وب سرویس
        /// </summary>
        public static string ServicesResponse([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.EnumTypesList.ServicesResponse;
            }
            return global::Resources.Enum.EnumTypesList.ResourceManager.GetString("ServicesResponse", resourceCulture);
        }
    }
}
namespace Resources.Enum.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class EnumTypesListKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: انواع دسترسی
        /// </summary>
        public const string AccessTypes = "AccessTypes";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: انواع واحد ارز
        /// </summary>
        public const string CurrencyUnits = "CurrencyUnits";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: انواع ثابت
        /// </summary>
        public const string EnumTypes = "EnumTypes";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: انواع فایل
        /// </summary>
        public const string FileTypes = "FileTypes";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: انواع ثبت لاگ سیستم
        /// </summary>
        public const string LogTypes = "LogTypes";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: انواع پیام ها
        /// </summary>
        public const string PageMessageTypes = "PageMessageTypes";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: انواع وضعیت درخواست
        /// </summary>
        public const string RequestStates = "RequestStates";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: انواع درخواست ها
        /// </summary>
        public const string RequestTypes = "RequestTypes";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: انواع نقش ها
        /// </summary>
        public const string Roles = "Roles";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: انواع پاسخ های وب سرویس
        /// </summary>
        public const string ServicesResponse = "ServicesResponse";
    }
}
