//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.Enum.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class FileTypes {
        
        /// <summary>
        ///   Looks up a localized string similar to: فایل های متنی
        /// </summary>
        public static string Articel([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.FileTypes.Articel;
            }
            return global::Resources.Enum.FileTypes.ResourceManager.GetString("Articel", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تصاویر
        /// </summary>
        public static string Picture([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.FileTypes.Picture;
            }
            return global::Resources.Enum.FileTypes.ResourceManager.GetString("Picture", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: فایل های صوتی و تصویری
        /// </summary>
        public static string Video([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.FileTypes.Video;
            }
            return global::Resources.Enum.FileTypes.ResourceManager.GetString("Video", resourceCulture);
        }
    }
}
namespace Resources.Enum.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class FileTypesKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: فایل های متنی
        /// </summary>
        public const string Articel = "Articel";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تصاویر
        /// </summary>
        public const string Picture = "Picture";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: فایل های صوتی و تصویری
        /// </summary>
        public const string Video = "Video";
    }
}
