//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.Enum.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class FinalApprove {
        
        /// <summary>
        ///   Looks up a localized string similar to: نهایی نشده
        /// </summary>
        public static string False([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.FinalApprove.False;
            }
            return global::Resources.Enum.FinalApprove.ResourceManager.GetString("False", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: نهایی شده
        /// </summary>
        public static string True([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.FinalApprove.True;
            }
            return global::Resources.Enum.FinalApprove.ResourceManager.GetString("True", resourceCulture);
        }
    }
}
namespace Resources.Enum.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class FinalApproveKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: نهایی نشده
        /// </summary>
        public const string False = "False";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: نهایی شده
        /// </summary>
        public const string True = "True";
    }
}
