//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.Enum.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Roles {
        
        /// <summary>
        ///   Looks up a localized string similar to: راهبر کل سامانه
        /// </summary>
        public static string Administrator([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.Roles.Administrator;
            }
            return global::Resources.Enum.Roles.ResourceManager.GetString("Administrator", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: کاربر صادر کننده فاکتور
        /// </summary>
        public static string ExporterOFInvoice([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.Roles.ExporterOFInvoice;
            }
            return global::Resources.Enum.Roles.ResourceManager.GetString("ExporterOFInvoice", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: اداره کل دامپزشکی کل کشور
        /// </summary>
        public static string GlobalVeterinaryOffice([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.Roles.GlobalVeterinaryOffice;
            }
            return global::Resources.Enum.Roles.ResourceManager.GetString("GlobalVeterinaryOffice", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: شرکت طراح
        /// </summary>
        public static string Programmer([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.Roles.Programmer;
            }
            return global::Resources.Enum.Roles.ResourceManager.GetString("Programmer", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: ادرات کل استان ها
        /// </summary>
        public static string ProvinceVeterinaryOffice([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.Roles.ProvinceVeterinaryOffice;
            }
            return global::Resources.Enum.Roles.ResourceManager.GetString("ProvinceVeterinaryOffice", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: کاربر گزارش گیری
        /// </summary>
        public static string Reporter([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.Roles.Reporter;
            }
            return global::Resources.Enum.Roles.ResourceManager.GetString("Reporter", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: کتربر معمولی
        /// </summary>
        public static string User([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.Roles.User;
            }
            return global::Resources.Enum.Roles.ResourceManager.GetString("User", resourceCulture);
        }
    }
}
namespace Resources.Enum.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class RolesKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: راهبر کل سامانه
        /// </summary>
        public const string Administrator = "Administrator";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: کاربر صادر کننده فاکتور
        /// </summary>
        public const string ExporterOFInvoice = "ExporterOFInvoice";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: اداره کل دامپزشکی کل کشور
        /// </summary>
        public const string GlobalVeterinaryOffice = "GlobalVeterinaryOffice";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: شرکت طراح
        /// </summary>
        public const string Programmer = "Programmer";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: ادرات کل استان ها
        /// </summary>
        public const string ProvinceVeterinaryOffice = "ProvinceVeterinaryOffice";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: کاربر گزارش گیری
        /// </summary>
        public const string Reporter = "Reporter";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: کتربر معمولی
        /// </summary>
        public const string User = "User";
    }
}
