//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.Enum.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ServicesResponse {
        
        /// <summary>
        ///   Looks up a localized string similar to: ConflictError
        /// </summary>
        public static string ConflictError([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.ServicesResponse.ConflictError;
            }
            return global::Resources.Enum.ServicesResponse.ResourceManager.GetString("ConflictError", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: DeleteError
        /// </summary>
        public static string DeleteError([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.ServicesResponse.DeleteError;
            }
            return global::Resources.Enum.ServicesResponse.ResourceManager.GetString("DeleteError", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Error
        /// </summary>
        public static string Error([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.ServicesResponse.Error;
            }
            return global::Resources.Enum.ServicesResponse.ResourceManager.GetString("Error", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: InsertError
        /// </summary>
        public static string InsertError([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.ServicesResponse.InsertError;
            }
            return global::Resources.Enum.ServicesResponse.ResourceManager.GetString("InsertError", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: ModelStateError
        /// </summary>
        public static string ModelStateError([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.ServicesResponse.ModelStateError;
            }
            return global::Resources.Enum.ServicesResponse.ResourceManager.GetString("ModelStateError", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: NotFoundError
        /// </summary>
        public static string NotFoundError([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.ServicesResponse.NotFoundError;
            }
            return global::Resources.Enum.ServicesResponse.ResourceManager.GetString("NotFoundError", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: NotResponse
        /// </summary>
        public static string NotResponse([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.ServicesResponse.NotResponse;
            }
            return global::Resources.Enum.ServicesResponse.ResourceManager.GetString("NotResponse", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Success
        /// </summary>
        public static string Success([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.ServicesResponse.Success;
            }
            return global::Resources.Enum.ServicesResponse.ResourceManager.GetString("Success", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: UpdateError
        /// </summary>
        public static string UpdateError([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.ServicesResponse.UpdateError;
            }
            return global::Resources.Enum.ServicesResponse.ResourceManager.GetString("UpdateError", resourceCulture);
        }
    }
}
namespace Resources.Enum.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ServicesResponseKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: ConflictError
        /// </summary>
        public const string ConflictError = "ConflictError";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: DeleteError
        /// </summary>
        public const string DeleteError = "DeleteError";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Error
        /// </summary>
        public const string Error = "Error";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: InsertError
        /// </summary>
        public const string InsertError = "InsertError";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: ModelStateError
        /// </summary>
        public const string ModelStateError = "ModelStateError";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: NotFoundError
        /// </summary>
        public const string NotFoundError = "NotFoundError";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: NotResponse
        /// </summary>
        public const string NotResponse = "NotResponse";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Success
        /// </summary>
        public const string Success = "Success";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: UpdateError
        /// </summary>
        public const string UpdateError = "UpdateError";
    }
}
