//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.Enum.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class SubSystems {
        
        /// <summary>
        ///   Looks up a localized string similar to: ترخیص
        /// </summary>
        public static string Clearance([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.SubSystems.Clearance;
            }
            return global::Resources.Enum.SubSystems.ResourceManager.GetString("Clearance", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: صدور مجوز بهداشتی واردات 
        /// </summary>
        public static string Import([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Enum.SubSystems.Import;
            }
            return global::Resources.Enum.SubSystems.ResourceManager.GetString("Import", resourceCulture);
        }
    }
}
namespace Resources.Enum.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class SubSystemsKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: ترخیص
        /// </summary>
        public const string Clearance = "Clearance";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: صدور مجوز بهداشتی واردات 
        /// </summary>
        public const string Import = "Import";
    }
}
