//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPS.IVOServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IVOServices.IIVOServices")]
    public interface IIVOServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIVOServices/Insert", ReplyAction="http://tempuri.org/IIVOServices/InsertResponse")]
        string Insert(string UserName, string Password, int SubSystem, string RecordNumber, int RequestState, string Message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIVOServices/Insert", ReplyAction="http://tempuri.org/IIVOServices/InsertResponse")]
        System.Threading.Tasks.Task<string> InsertAsync(string UserName, string Password, int SubSystem, string RecordNumber, int RequestState, string Message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIVOServicesChannel : OPS.IVOServices.IIVOServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IVOServicesClient : System.ServiceModel.ClientBase<OPS.IVOServices.IIVOServices>, OPS.IVOServices.IIVOServices {
        
        public IVOServicesClient() {
        }
        
        public IVOServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IVOServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IVOServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IVOServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Insert(string UserName, string Password, int SubSystem, string RecordNumber, int RequestState, string Message) {
            return base.Channel.Insert(UserName, Password, SubSystem, RecordNumber, RequestState, Message);
        }
        
        public System.Threading.Tasks.Task<string> InsertAsync(string UserName, string Password, int SubSystem, string RecordNumber, int RequestState, string Message) {
            return base.Channel.InsertAsync(UserName, Password, SubSystem, RecordNumber, RequestState, Message);
        }
    }
}
