//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.ViewModel.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class MarketingTransactionViewModel {
        
        /// <summary>
        ///   Looks up a localized string similar to: مبلغ کمیسیون دریافتی
        /// </summary>
        public static string CommissionAmount([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.ViewModel.MarketingTransactionViewModel.CommissionAmount;
            }
            return global::Resources.ViewModel.MarketingTransactionViewModel.ResourceManager.GetString("CommissionAmount", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: نام کارخانه تولید کننده
        /// </summary>
        public static string FactoryNameString([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.ViewModel.MarketingTransactionViewModel.FactoryNameString;
            }
            return global::Resources.ViewModel.MarketingTransactionViewModel.ResourceManager.GetString("FactoryNameString", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: نوع بسته بندی محصول
        /// </summary>
        public static string PackageTypeString([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.ViewModel.MarketingTransactionViewModel.PackageTypeString;
            }
            return global::Resources.ViewModel.MarketingTransactionViewModel.ResourceManager.GetString("PackageTypeString", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: نام محصول
        /// </summary>
        public static string ProductNameString([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.ViewModel.MarketingTransactionViewModel.ProductNameString;
            }
            return global::Resources.ViewModel.MarketingTransactionViewModel.ResourceManager.GetString("ProductNameString", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: نوع محصول
        /// </summary>
        public static string ProductTypeString([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.ViewModel.MarketingTransactionViewModel.ProductTypeString;
            }
            return global::Resources.ViewModel.MarketingTransactionViewModel.ResourceManager.GetString("ProductTypeString", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تناژ محصول
        /// </summary>
        public static string Tonnage([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.ViewModel.MarketingTransactionViewModel.Tonnage;
            }
            return global::Resources.ViewModel.MarketingTransactionViewModel.ResourceManager.GetString("Tonnage", resourceCulture);
        }
    }
}
namespace Resources.ViewModel.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class MarketingTransactionViewModelKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: مبلغ کمیسیون دریافتی
        /// </summary>
        public const string CommissionAmount = "CommissionAmount";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: نام کارخانه تولید کننده
        /// </summary>
        public const string FactoryNameString = "FactoryNameString";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: نوع بسته بندی محصول
        /// </summary>
        public const string PackageTypeString = "PackageTypeString";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: نام محصول
        /// </summary>
        public const string ProductNameString = "ProductNameString";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: نوع محصول
        /// </summary>
        public const string ProductTypeString = "ProductTypeString";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تناژ محصول
        /// </summary>
        public const string Tonnage = "Tonnage";
    }
}
