//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.ViewModel.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class RechargewalletUser {
        
        /// <summary>
        ///   Looks up a localized string similar to: مقدار افزایش موجودی
        /// </summary>
        public static string ChargeAmount([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.ViewModel.RechargewalletUser.ChargeAmount;
            }
            return global::Resources.ViewModel.RechargewalletUser.ResourceManager.GetString("ChargeAmount", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: توضیحات
        /// </summary>
        public static string Description([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.ViewModel.RechargewalletUser.Description;
            }
            return global::Resources.ViewModel.RechargewalletUser.ResourceManager.GetString("Description", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: شماره موبایل کاربر
        /// </summary>
        public static string PhoneNumber([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.ViewModel.RechargewalletUser.PhoneNumber;
            }
            return global::Resources.ViewModel.RechargewalletUser.ResourceManager.GetString("PhoneNumber", resourceCulture);
        }
    }
}
namespace Resources.ViewModel.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class RechargewalletUserKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: مقدار افزایش موجودی
        /// </summary>
        public const string ChargeAmount = "ChargeAmount";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: توضیحات
        /// </summary>
        public const string Description = "Description";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: شماره موبایل کاربر
        /// </summary>
        public const string PhoneNumber = "PhoneNumber";
    }
}
