// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace OPS.Areas.Administrator.Controllers
{
    public partial class RequestController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public RequestController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RequestController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Search()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Search);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult DetailsInvoiceNumber()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.DetailsInvoiceNumber);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Edit()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult EditIVO()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.EditIVO);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult GetTransactionReportByPageNumber()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.GetTransactionReportByPageNumber);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult UpAmountPaid()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.UpAmountPaid);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Incomplete()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Incomplete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult DetailsByTracingCode()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.DetailsByTracingCode);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ViewFiles()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ViewFiles);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult GetCities()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.GetCities);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult PrintNewFactor()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.PrintNewFactor);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult PrintDepositNumber()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.PrintDepositNumber);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult AddPayment()
        {
            return new T4MVC_JsonResult(Area, Name, ActionNames.AddPayment);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public RequestController Actions { get { return MVC.Administrator.Request; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Administrator";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Request";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Request";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Search = "Search";
            public readonly string GetRequests = "GetRequests";
            public readonly string DetailsInvoiceNumber = "DetailsInvoiceNumber";
            public readonly string Edit = "Edit";
            public readonly string EditIVO = "EditIVO";
            public readonly string GetTransactionReportByPageNumber = "GetTransactionReportByPageNumber";
            public readonly string UpAmountPaid = "UpAmountPaid";
            public readonly string Incomplete = "Incomplete";
            public readonly string DetailsByTracingCode = "DetailsByTracingCode";
            public readonly string ViewFiles = "ViewFiles";
            public readonly string Download = "Download";
            public readonly string GetCities = "GetCities";
            public readonly string PrintNewFactor = "PrintNewFactor";
            public readonly string PrintDepositNumber = "PrintDepositNumber";
            public readonly string AddPayment = "AddPayment";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Search = "Search";
            public const string GetRequests = "GetRequests";
            public const string DetailsInvoiceNumber = "DetailsInvoiceNumber";
            public const string Edit = "Edit";
            public const string EditIVO = "EditIVO";
            public const string GetTransactionReportByPageNumber = "GetTransactionReportByPageNumber";
            public const string UpAmountPaid = "UpAmountPaid";
            public const string Incomplete = "Incomplete";
            public const string DetailsByTracingCode = "DetailsByTracingCode";
            public const string ViewFiles = "ViewFiles";
            public const string Download = "Download";
            public const string GetCities = "GetCities";
            public const string PrintNewFactor = "PrintNewFactor";
            public const string PrintDepositNumber = "PrintDepositNumber";
            public const string AddPayment = "AddPayment";
        }


        static readonly ActionParamsClass_Search s_params_Search = new ActionParamsClass_Search();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Search SearchParams { get { return s_params_Search; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Search
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_DetailsInvoiceNumber s_params_DetailsInvoiceNumber = new ActionParamsClass_DetailsInvoiceNumber();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DetailsInvoiceNumber DetailsInvoiceNumberParams { get { return s_params_DetailsInvoiceNumber; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DetailsInvoiceNumber
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Edit s_params_Edit = new ActionParamsClass_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Edit EditParams { get { return s_params_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Edit
        {
            public readonly string id = "id";
            public readonly string request = "request";
            public readonly string submit = "submit";
        }
        static readonly ActionParamsClass_EditIVO s_params_EditIVO = new ActionParamsClass_EditIVO();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditIVO EditIVOParams { get { return s_params_EditIVO; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditIVO
        {
            public readonly string id = "id";
            public readonly string request = "request";
        }
        static readonly ActionParamsClass_GetTransactionReportByPageNumber s_params_GetTransactionReportByPageNumber = new ActionParamsClass_GetTransactionReportByPageNumber();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetTransactionReportByPageNumber GetTransactionReportByPageNumberParams { get { return s_params_GetTransactionReportByPageNumber; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetTransactionReportByPageNumber
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_UpAmountPaid s_params_UpAmountPaid = new ActionParamsClass_UpAmountPaid();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpAmountPaid UpAmountPaidParams { get { return s_params_UpAmountPaid; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpAmountPaid
        {
            public readonly string id = "id";
            public readonly string request = "request";
            public readonly string submit = "submit";
        }
        static readonly ActionParamsClass_Incomplete s_params_Incomplete = new ActionParamsClass_Incomplete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Incomplete IncompleteParams { get { return s_params_Incomplete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Incomplete
        {
            public readonly string RecordNumber = "RecordNumber";
            public readonly string SystemMessage = "SystemMessage";
        }
        static readonly ActionParamsClass_DetailsByTracingCode s_params_DetailsByTracingCode = new ActionParamsClass_DetailsByTracingCode();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DetailsByTracingCode DetailsByTracingCodeParams { get { return s_params_DetailsByTracingCode; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DetailsByTracingCode
        {
            public readonly string tracingcode = "tracingcode";
        }
        static readonly ActionParamsClass_ViewFiles s_params_ViewFiles = new ActionParamsClass_ViewFiles();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ViewFiles ViewFilesParams { get { return s_params_ViewFiles; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ViewFiles
        {
            public readonly string Id = "Id";
        }
        static readonly ActionParamsClass_GetCities s_params_GetCities = new ActionParamsClass_GetCities();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetCities GetCitiesParams { get { return s_params_GetCities; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetCities
        {
            public readonly string provinceId = "provinceId";
        }
        static readonly ActionParamsClass_PrintNewFactor s_params_PrintNewFactor = new ActionParamsClass_PrintNewFactor();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PrintNewFactor PrintNewFactorParams { get { return s_params_PrintNewFactor; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PrintNewFactor
        {
            public readonly string invoiceNumber = "invoiceNumber";
        }
        static readonly ActionParamsClass_PrintDepositNumber s_params_PrintDepositNumber = new ActionParamsClass_PrintDepositNumber();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PrintDepositNumber PrintDepositNumberParams { get { return s_params_PrintDepositNumber; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PrintDepositNumber
        {
            public readonly string invoiceNumber = "invoiceNumber";
        }
        static readonly ActionParamsClass_AddPayment s_params_AddPayment = new ActionParamsClass_AddPayment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddPayment AddPaymentParams { get { return s_params_AddPayment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddPayment
        {
            public readonly string data = "data";
            public readonly string Id = "Id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Edit = "Edit";
                public readonly string EditIVO = "EditIVO";
                public readonly string Incomplete = "Incomplete";
                public readonly string Index = "Index";
                public readonly string PaymentReport = "PaymentReport";
                public readonly string PrintDepositNumber = "PrintDepositNumber";
                public readonly string PrintFactor = "PrintFactor";
                public readonly string PrintNewFactor = "PrintNewFactor";
                public readonly string UpAmountPaid = "UpAmountPaid";
            }
            public readonly string Edit = "~/Areas/Administrator/Views/Request/Edit.cshtml";
            public readonly string EditIVO = "~/Areas/Administrator/Views/Request/EditIVO.cshtml";
            public readonly string Incomplete = "~/Areas/Administrator/Views/Request/Incomplete.cshtml";
            public readonly string Index = "~/Areas/Administrator/Views/Request/Index.cshtml";
            public readonly string PaymentReport = "~/Areas/Administrator/Views/Request/PaymentReport.cshtml";
            public readonly string PrintDepositNumber = "~/Areas/Administrator/Views/Request/PrintDepositNumber.cshtml";
            public readonly string PrintFactor = "~/Areas/Administrator/Views/Request/PrintFactor.cshtml";
            public readonly string PrintNewFactor = "~/Areas/Administrator/Views/Request/PrintNewFactor.cshtml";
            public readonly string UpAmountPaid = "~/Areas/Administrator/Views/Request/UpAmountPaid.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_RequestController : OPS.Areas.Administrator.Controllers.RequestController
    {
        public T4MVC_RequestController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Search(ViewModels.Areas.Administrator.Request.SearchViewModel viewModel)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult GetRequests()
        {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.GetRequests);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult DetailsInvoiceNumber(int id)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.DetailsInvoiceNumber);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(System.Guid id)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult EditIVO(System.Guid id)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.EditIVO);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult GetTransactionReportByPageNumber(System.Guid id)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetTransactionReportByPageNumber);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult UpAmountPaid(System.Guid id)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.UpAmountPaid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult UpAmountPaid(ViewModels.Areas.Administrator.Request.UpAmountPaidViewModel request, string submit)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.UpAmountPaid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "submit", submit);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Incomplete(string RecordNumber, string SystemMessage)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Incomplete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "RecordNumber", RecordNumber);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "SystemMessage", SystemMessage);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(ViewModels.Areas.Administrator.Request.EditViewModel request, string submit)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "submit", submit);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult EditIVO(ViewModels.Areas.Administrator.Request.EditViewModel request)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.EditIVO);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult DetailsByTracingCode(string tracingcode)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.DetailsByTracingCode);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "tracingcode", tracingcode);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ViewFiles(string Id)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ViewFiles);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            return callInfo;
        }

        public override System.Web.Mvc.FileContentResult Download()
        {
            var callInfo = new T4MVC_FileContentResult(Area, Name, ActionNames.Download);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult GetCities(System.Guid provinceId)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetCities);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "provinceId", provinceId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult PrintNewFactor(int invoiceNumber)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.PrintNewFactor);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "invoiceNumber", invoiceNumber);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult PrintDepositNumber(int invoiceNumber)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.PrintDepositNumber);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "invoiceNumber", invoiceNumber);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult AddPayment(OPS.Areas.Administrator.Controllers.PCPOS_Res data, System.Guid Id)
        {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.AddPayment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
