// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace OPS.Areas.Administrator.Controllers
{
    public partial class PreInvoiceController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PreInvoiceController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PreInvoiceController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Search()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Search);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult FinalApproveInvoice()
        {
            return new T4MVC_JsonResult(Area, Name, ActionNames.FinalApproveInvoice);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult RejectInvoice()
        {
            return new T4MVC_JsonResult(Area, Name, ActionNames.RejectInvoice);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult GetLivePriceCalc()
        {
            return new T4MVC_JsonResult(Area, Name, ActionNames.GetLivePriceCalc);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult GetCarrierInfo()
        {
            return new T4MVC_JsonResult(Area, Name, ActionNames.GetCarrierInfo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult GetCarriersByProduct()
        {
            return new T4MVC_JsonResult(Area, Name, ActionNames.GetCarriersByProduct);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PreInvoiceController Actions { get { return MVC.Administrator.PreInvoice; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Administrator";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "PreInvoice";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "PreInvoice";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string GetRequests = "GetRequests";
            public readonly string Search = "Search";
            public readonly string FinalApproveInvoice = "FinalApproveInvoice";
            public readonly string RejectInvoice = "RejectInvoice";
            public readonly string Create = "Create";
            public readonly string GetLivePriceCalc = "GetLivePriceCalc";
            public readonly string GetCarrierInfo = "GetCarrierInfo";
            public readonly string GetCarriersByProduct = "GetCarriersByProduct";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string GetRequests = "GetRequests";
            public const string Search = "Search";
            public const string FinalApproveInvoice = "FinalApproveInvoice";
            public const string RejectInvoice = "RejectInvoice";
            public const string Create = "Create";
            public const string GetLivePriceCalc = "GetLivePriceCalc";
            public const string GetCarrierInfo = "GetCarrierInfo";
            public const string GetCarriersByProduct = "GetCarriersByProduct";
        }


        static readonly ActionParamsClass_Search s_params_Search = new ActionParamsClass_Search();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Search SearchParams { get { return s_params_Search; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Search
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_FinalApproveInvoice s_params_FinalApproveInvoice = new ActionParamsClass_FinalApproveInvoice();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_FinalApproveInvoice FinalApproveInvoiceParams { get { return s_params_FinalApproveInvoice; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_FinalApproveInvoice
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_RejectInvoice s_params_RejectInvoice = new ActionParamsClass_RejectInvoice();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RejectInvoice RejectInvoiceParams { get { return s_params_RejectInvoice; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RejectInvoice
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Create s_params_Create = new ActionParamsClass_Create();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Create CreateParams { get { return s_params_Create; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Create
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_GetLivePriceCalc s_params_GetLivePriceCalc = new ActionParamsClass_GetLivePriceCalc();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetLivePriceCalc GetLivePriceCalcParams { get { return s_params_GetLivePriceCalc; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetLivePriceCalc
        {
            public readonly string productNameId = "productNameId";
            public readonly string productTypeId = "productTypeId";
            public readonly string packageTypeId = "packageTypeId";
            public readonly string factoryNameId = "factoryNameId";
            public readonly string tonnage = "tonnage";
        }
        static readonly ActionParamsClass_GetCarrierInfo s_params_GetCarrierInfo = new ActionParamsClass_GetCarrierInfo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetCarrierInfo GetCarrierInfoParams { get { return s_params_GetCarrierInfo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetCarrierInfo
        {
            public readonly string carrierId = "carrierId";
        }
        static readonly ActionParamsClass_GetCarriersByProduct s_params_GetCarriersByProduct = new ActionParamsClass_GetCarriersByProduct();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetCarriersByProduct GetCarriersByProductParams { get { return s_params_GetCarriersByProduct; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetCarriersByProduct
        {
            public readonly string productNameId = "productNameId";
            public readonly string productTypeId = "productTypeId";
            public readonly string packageTypeId = "packageTypeId";
            public readonly string factoryNameId = "factoryNameId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Create = "Create";
                public readonly string Index = "Index";
            }
            public readonly string Create = "~/Areas/Administrator/Views/PreInvoice/Create.cshtml";
            public readonly string Index = "~/Areas/Administrator/Views/PreInvoice/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_PreInvoiceController : OPS.Areas.Administrator.Controllers.PreInvoiceController
    {
        public T4MVC_PreInvoiceController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult GetRequests()
        {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.GetRequests);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Search(ViewModels.Areas.Administrator.Request.IndexViewModel viewModel)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult FinalApproveInvoice(System.Guid id)
        {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.FinalApproveInvoice);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult RejectInvoice(System.Guid id)
        {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.RejectInvoice);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Create()
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Create);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Create(ViewModels.Areas.Administrator.PreInvoice.CreateViewModel viewModel)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Create);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult GetLivePriceCalc(System.Guid productNameId, System.Guid productTypeId, System.Guid packageTypeId, System.Guid factoryNameId, decimal tonnage)
        {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.GetLivePriceCalc);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "productNameId", productNameId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "productTypeId", productTypeId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "packageTypeId", packageTypeId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "factoryNameId", factoryNameId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "tonnage", tonnage);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult GetCarrierInfo(System.Guid carrierId)
        {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.GetCarrierInfo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "carrierId", carrierId);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult GetCarriersByProduct(System.Guid productNameId, System.Guid productTypeId, System.Guid packageTypeId, System.Guid factoryNameId)
        {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.GetCarriersByProduct);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "productNameId", productNameId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "productTypeId", productTypeId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "packageTypeId", packageTypeId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "factoryNameId", factoryNameId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
