// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace OPS.Areas.Administrator.Controllers
{
    public partial class UserController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public UserController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected UserController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Search()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Search);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult GetCities()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.GetCities);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Detail()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Detail);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Edit()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Delete()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Delete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult DeleteConfirmed()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.DeleteConfirmed);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ChangePassword()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ChangePassword);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult CheckPersonValidation()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.CheckPersonValidation);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult CheckPostalCodeValidation()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.CheckPostalCodeValidation);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Authenticate()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Authenticate);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult DownloadUserExcelGetByid()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.DownloadUserExcelGetByid);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Paymentwallet()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Paymentwallet);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public UserController Actions { get { return MVC.Administrator.User; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Administrator";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "User";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "User";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Search = "Search";
            public readonly string GetUsers = "GetUsers";
            public readonly string Create = "Create";
            public readonly string GetCities = "GetCities";
            public readonly string Detail = "Detail";
            public readonly string Edit = "Edit";
            public readonly string Delete = "Delete";
            public readonly string DeleteConfirmed = "Delete";
            public readonly string ChangePassword = "ChangePassword";
            public readonly string AccessManagement = "AccessManagement";
            public readonly string CheckPersonValidation = "CheckPersonValidation";
            public readonly string CheckPostalCodeValidation = "CheckPostalCodeValidation";
            public readonly string Authenticate = "Authenticate";
            public readonly string DownloadUserExcel = "DownloadUserExcel";
            public readonly string DownloadUserExcelGetByid = "DownloadUserExcelGetByid";
            public readonly string Paymentwallet = "Paymentwallet";
            public readonly string SendSMSdebtor = "SendSMSdebtor";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Search = "Search";
            public const string GetUsers = "GetUsers";
            public const string Create = "Create";
            public const string GetCities = "GetCities";
            public const string Detail = "Detail";
            public const string Edit = "Edit";
            public const string Delete = "Delete";
            public const string DeleteConfirmed = "Delete";
            public const string ChangePassword = "ChangePassword";
            public const string AccessManagement = "AccessManagement";
            public const string CheckPersonValidation = "CheckPersonValidation";
            public const string CheckPostalCodeValidation = "CheckPostalCodeValidation";
            public const string Authenticate = "Authenticate";
            public const string DownloadUserExcel = "DownloadUserExcel";
            public const string DownloadUserExcelGetByid = "DownloadUserExcelGetByid";
            public const string Paymentwallet = "Paymentwallet";
            public const string SendSMSdebtor = "SendSMSdebtor";
        }


        static readonly ActionParamsClass_Search s_params_Search = new ActionParamsClass_Search();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Search SearchParams { get { return s_params_Search; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Search
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_GetCities s_params_GetCities = new ActionParamsClass_GetCities();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetCities GetCitiesParams { get { return s_params_GetCities; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetCities
        {
            public readonly string provinceId = "provinceId";
        }
        static readonly ActionParamsClass_Create s_params_Create = new ActionParamsClass_Create();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Create CreateParams { get { return s_params_Create; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Create
        {
            public readonly string user = "user";
        }
        static readonly ActionParamsClass_Detail s_params_Detail = new ActionParamsClass_Detail();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Detail DetailParams { get { return s_params_Detail; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Detail
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Edit s_params_Edit = new ActionParamsClass_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Edit EditParams { get { return s_params_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Edit
        {
            public readonly string id = "id";
            public readonly string user = "user";
        }
        static readonly ActionParamsClass_Delete s_params_Delete = new ActionParamsClass_Delete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Delete DeleteParams { get { return s_params_Delete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Delete
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DeleteConfirmed s_params_DeleteConfirmed = new ActionParamsClass_DeleteConfirmed();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteConfirmed DeleteConfirmedParams { get { return s_params_DeleteConfirmed; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteConfirmed
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ChangePassword s_params_ChangePassword = new ActionParamsClass_ChangePassword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ChangePassword ChangePasswordParams { get { return s_params_ChangePassword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ChangePassword
        {
            public readonly string id = "id";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_CheckPersonValidation s_params_CheckPersonValidation = new ActionParamsClass_CheckPersonValidation();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CheckPersonValidation CheckPersonValidationParams { get { return s_params_CheckPersonValidation; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CheckPersonValidation
        {
            public readonly string NationalCode = "NationalCode";
            public readonly string birthDate = "birthDate";
        }
        static readonly ActionParamsClass_CheckPostalCodeValidation s_params_CheckPostalCodeValidation = new ActionParamsClass_CheckPostalCodeValidation();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CheckPostalCodeValidation CheckPostalCodeValidationParams { get { return s_params_CheckPostalCodeValidation; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CheckPostalCodeValidation
        {
            public readonly string PostalCode = "PostalCode";
        }
        static readonly ActionParamsClass_Authenticate s_params_Authenticate = new ActionParamsClass_Authenticate();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Authenticate AuthenticateParams { get { return s_params_Authenticate; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Authenticate
        {
            public readonly string authenticateViewModel = "authenticateViewModel";
        }
        static readonly ActionParamsClass_DownloadUserExcelGetByid s_params_DownloadUserExcelGetByid = new ActionParamsClass_DownloadUserExcelGetByid();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DownloadUserExcelGetByid DownloadUserExcelGetByidParams { get { return s_params_DownloadUserExcelGetByid; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DownloadUserExcelGetByid
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Paymentwallet s_params_Paymentwallet = new ActionParamsClass_Paymentwallet();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Paymentwallet PaymentwalletParams { get { return s_params_Paymentwallet; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Paymentwallet
        {
            public readonly string id = "id";
            public readonly string page = "page";
            public readonly string rechargewalletUser = "rechargewalletUser";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string AccessManagement = "AccessManagement";
                public readonly string ChangePassword = "ChangePassword";
                public readonly string Create = "Create";
                public readonly string Delete = "Delete";
                public readonly string Detail = "Detail";
                public readonly string Edit = "Edit";
                public readonly string Index = "Index";
                public readonly string Paymentwallet = "Paymentwallet";
            }
            public readonly string AccessManagement = "~/Areas/Administrator/Views/User/AccessManagement.cshtml";
            public readonly string ChangePassword = "~/Areas/Administrator/Views/User/ChangePassword.cshtml";
            public readonly string Create = "~/Areas/Administrator/Views/User/Create.cshtml";
            public readonly string Delete = "~/Areas/Administrator/Views/User/Delete.cshtml";
            public readonly string Detail = "~/Areas/Administrator/Views/User/Detail.cshtml";
            public readonly string Edit = "~/Areas/Administrator/Views/User/Edit.cshtml";
            public readonly string Index = "~/Areas/Administrator/Views/User/Index.cshtml";
            public readonly string Paymentwallet = "~/Areas/Administrator/Views/User/Paymentwallet.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_UserController : OPS.Areas.Administrator.Controllers.UserController
    {
        public T4MVC_UserController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Search(ViewModels.Areas.Administrator.User.SearchViewModel viewModel)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult GetUsers()
        {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.GetUsers);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Create()
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Create);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult GetCities(System.Guid provinceId)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetCities);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "provinceId", provinceId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Create(ViewModels.Areas.Administrator.User.CreateViewModel user)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Create);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "user", user);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Detail(System.Guid id)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Detail);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(System.Guid id)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(ViewModels.Areas.Administrator.User.EditViewModel user)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "user", user);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Delete(System.Guid id)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Delete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult DeleteConfirmed(System.Guid id)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.DeleteConfirmed);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ChangePassword(System.Guid id)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ChangePassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ChangePassword(ViewModels.Areas.Administrator.User.ChangePasswordViewModel viewModel)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ChangePassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AccessManagement()
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AccessManagement);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CheckPersonValidation(string NationalCode, string birthDate)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CheckPersonValidation);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "NationalCode", NationalCode);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "birthDate", birthDate);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CheckPostalCodeValidation(string PostalCode)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CheckPostalCodeValidation);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "PostalCode", PostalCode);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Authenticate(ViewModels.Areas.Administrator.User.AuthenticateViewModel authenticateViewModel)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Authenticate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "authenticateViewModel", authenticateViewModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult DownloadUserExcel()
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.DownloadUserExcel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult DownloadUserExcelGetByid(System.Guid id)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.DownloadUserExcelGetByid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Paymentwallet(System.Guid id, int? page)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Paymentwallet);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Paymentwallet(ViewModels.Areas.Administrator.User.RechargewalletUser rechargewalletUser)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Paymentwallet);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rechargewalletUser", rechargewalletUser);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SendSMSdebtor()
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SendSMSdebtor);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
