// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace OPS.Areas.Carrier.Controllers
{
    public partial class RequestController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public RequestController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RequestController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Search()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Search);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult LoadCargo()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.LoadCargo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult SetAsLoaded()
        {
            return new T4MVC_JsonResult(Area, Name, ActionNames.SetAsLoaded);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SetAsDelivered()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.SetAsDelivered);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public RequestController Actions { get { return MVC.Carrier.Request; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Carrier";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Request";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Request";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string GetRequests = "GetRequests";
            public readonly string Search = "Search";
            public readonly string LoadCargo = "LoadCargo";
            public readonly string SetAsLoaded = "SetAsLoaded";
            public readonly string SetAsDelivered = "SetAsDelivered";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string GetRequests = "GetRequests";
            public const string Search = "Search";
            public const string LoadCargo = "LoadCargo";
            public const string SetAsLoaded = "SetAsLoaded";
            public const string SetAsDelivered = "SetAsDelivered";
        }


        static readonly ActionParamsClass_Search s_params_Search = new ActionParamsClass_Search();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Search SearchParams { get { return s_params_Search; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Search
        {
            public readonly string viewModel = "viewModel";
            public readonly string gridTab = "gridTab";
        }
        static readonly ActionParamsClass_LoadCargo s_params_LoadCargo = new ActionParamsClass_LoadCargo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LoadCargo LoadCargoParams { get { return s_params_LoadCargo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LoadCargo
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_SetAsLoaded s_params_SetAsLoaded = new ActionParamsClass_SetAsLoaded();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SetAsLoaded SetAsLoadedParams { get { return s_params_SetAsLoaded; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SetAsLoaded
        {
            public readonly string id = "id";
            public readonly string driverName = "driverName";
            public readonly string driverMobile = "driverMobile";
            public readonly string licensePlate = "licensePlate";
        }
        static readonly ActionParamsClass_SetAsDelivered s_params_SetAsDelivered = new ActionParamsClass_SetAsDelivered();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SetAsDelivered SetAsDeliveredParams { get { return s_params_SetAsDelivered; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SetAsDelivered
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
                public readonly string LoadCargo = "LoadCargo";
            }
            public readonly string Index = "~/Areas/Carrier/Views/Request/Index.cshtml";
            public readonly string LoadCargo = "~/Areas/Carrier/Views/Request/LoadCargo.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_RequestController : OPS.Areas.Carrier.Controllers.RequestController
    {
        public T4MVC_RequestController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult GetRequests()
        {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.GetRequests);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Search(ViewModels.Areas.Administrator.Request.IndexViewModel viewModel, int gridTab)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "gridTab", gridTab);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult LoadCargo(System.Guid id)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.LoadCargo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult SetAsLoaded(System.Guid id, string driverName, string driverMobile, string licensePlate)
        {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.SetAsLoaded);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "driverName", driverName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "driverMobile", driverMobile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "licensePlate", licensePlate);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SetAsDelivered(System.Guid id)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SetAsDelivered);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
