// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace OPS.Controllers
{
    public partial class ErrorController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ErrorController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ViewResult Display()
        {
            return new T4MVC_ViewResult(Area, Name, ActionNames.Display);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ErrorController Actions { get { return MVC.Error; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Error";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Error";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string BadRequest = "BadRequest";
            public readonly string AccessDenied = "AccessDenied";
            public readonly string InvalidRequest = "InvalidRequest";
            public readonly string Forbidden = "Forbidden";
            public readonly string Display = "Display";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string BadRequest = "BadRequest";
            public const string AccessDenied = "AccessDenied";
            public const string InvalidRequest = "InvalidRequest";
            public const string Forbidden = "Forbidden";
            public const string Display = "Display";
        }


        static readonly ActionParamsClass_Display s_params_Display = new ActionParamsClass_Display();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Display DisplayParams { get { return s_params_Display; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Display
        {
            public readonly string code = "code";
            public readonly string lincCode = "lincCode";
            public readonly string exsption = "exsption";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string AccessDenied = "AccessDenied";
                public readonly string Display = "Display";
                public readonly string InvalidRequest = "InvalidRequest";
            }
            public readonly string AccessDenied = "~/Views/Error/AccessDenied.cshtml";
            public readonly string Display = "~/Views/Error/Display.cshtml";
            public readonly string InvalidRequest = "~/Views/Error/InvalidRequest.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_ErrorController : OPS.Controllers.ErrorController
    {
        public T4MVC_ErrorController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult BadRequest()
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.BadRequest);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AccessDenied()
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AccessDenied);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult InvalidRequest()
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.InvalidRequest);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Forbidden()
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Forbidden);
            return callInfo;
        }

        public override System.Web.Mvc.ViewResult Display(System.Net.HttpStatusCode? code)
        {
            var callInfo = new T4MVC_ViewResult(Area, Name, ActionNames.Display);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "code", code);
            return callInfo;
        }

        public override System.Web.Mvc.ViewResult Display(System.Net.HttpStatusCode? code, int lincCode)
        {
            var callInfo = new T4MVC_ViewResult(Area, Name, ActionNames.Display);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "code", code);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lincCode", lincCode);
            return callInfo;
        }

        public override System.Web.Mvc.ViewResult Display(string exsption, int lincCode)
        {
            var callInfo = new T4MVC_ViewResult(Area, Name, ActionNames.Display);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "exsption", exsption);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lincCode", lincCode);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
