// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class PaymentController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string GetRequest = "GetRequest";
                public readonly string GlobalPayment = "GlobalPayment";
                public readonly string Index = "Index";
                public readonly string MerchantCommit = "MerchantCommit";
                public readonly string MerchantCommit1 = "MerchantCommit1";
                public readonly string MerchantCommitByInvoiceNumber = "MerchantCommitByInvoiceNumber";
                public readonly string MerchantCommitFile = "MerchantCommitFile";
                public readonly string NewMerchantCommit = "NewMerchantCommit";
                public readonly string PrintDepositNumber = "PrintDepositNumber";
                public readonly string PrintDepositNumberNew = "PrintDepositNumberNew";
                public readonly string PrintFinalPayment = "PrintFinalPayment";
                public readonly string ShowPaymentInvoice = "ShowPaymentInvoice";
                public readonly string TestAction = "TestAction";
                public readonly string VerifyTransaction = "VerifyTransaction";
            }
            public readonly string GetRequest = "~/Views/Payment/GetRequest.cshtml";
            public readonly string GlobalPayment = "~/Views/Payment/GlobalPayment.cshtml";
            public readonly string Index = "~/Views/Payment/Index.cshtml";
            public readonly string MerchantCommit = "~/Views/Payment/MerchantCommit.cshtml";
            public readonly string MerchantCommit1 = "~/Views/Payment/MerchantCommit1.cshtml";
            public readonly string MerchantCommitByInvoiceNumber = "~/Views/Payment/MerchantCommitByInvoiceNumber.cshtml";
            public readonly string MerchantCommitFile = "~/Views/Payment/MerchantCommitFile.cshtml";
            public readonly string NewMerchantCommit = "~/Views/Payment/NewMerchantCommit.cshtml";
            public readonly string PrintDepositNumber = "~/Views/Payment/PrintDepositNumber.cshtml";
            public readonly string PrintDepositNumberNew = "~/Views/Payment/PrintDepositNumberNew.cshtml";
            public readonly string PrintFinalPayment = "~/Views/Payment/PrintFinalPayment.cshtml";
            public readonly string ShowPaymentInvoice = "~/Views/Payment/ShowPaymentInvoice.cshtml";
            public readonly string TestAction = "~/Views/Payment/TestAction.cshtml";
            public readonly string VerifyTransaction = "~/Views/Payment/VerifyTransaction.cshtml";
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
