//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.Message.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class HeadOfFactor {
        
        /// <summary>
        ///   Looks up a localized string similar to: حذف فاکتور
        /// </summary>
        public static string Delete([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Message.HeadOfFactor.Delete;
            }
            return global::Resources.Message.HeadOfFactor.ResourceManager.GetString("Delete", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: تایید نهایی و ارجاع به بخش درخواست ها جهت صدور شناسه واریز
        /// </summary>
        public static string FinalApprove([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Message.HeadOfFactor.FinalApprove;
            }
            return global::Resources.Message.HeadOfFactor.ResourceManager.GetString("FinalApprove", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: اعلام نواقصی
        /// </summary>
        public static string Incomplete([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Message.HeadOfFactor.Incomplete;
            }
            return global::Resources.Message.HeadOfFactor.ResourceManager.GetString("Incomplete", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: ثبت اولیه و در حال بررسی
        /// </summary>
        public static string Insert([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Message.HeadOfFactor.Insert;
            }
            return global::Resources.Message.HeadOfFactor.ResourceManager.GetString("Insert", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: بروزرسانی اطلاعات فاکتور
        /// </summary>
        public static string Update([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Message.HeadOfFactor.Update;
            }
            return global::Resources.Message.HeadOfFactor.ResourceManager.GetString("Update", resourceCulture);
        }
    }
}
namespace Resources.Message.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class HeadOfFactorKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: حذف فاکتور
        /// </summary>
        public const string Delete = "Delete";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: تایید نهایی و ارجاع به بخش درخواست ها جهت صدور شناسه واریز
        /// </summary>
        public const string FinalApprove = "FinalApprove";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: اعلام نواقصی
        /// </summary>
        public const string Incomplete = "Incomplete";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: ثبت اولیه و در حال بررسی
        /// </summary>
        public const string Insert = "Insert";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: بروزرسانی اطلاعات فاکتور
        /// </summary>
        public const string Update = "Update";
    }
}
