//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Message {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class User {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Message.User", typeof(User).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشانی پست الکترونيکی تکراری است! لطفا از نشانی پست الکترونيکی ديگری استفاده نماييد..
        /// </summary>
        public static string Error001 {
            get {
                return ResourceManager.GetString("Error001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چنين نشانی پست الکترونيکی در سيستم موجود نمی‌باشد!.
        /// </summary>
        public static string Error002 {
            get {
                return ResourceManager.GetString("Error002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه کاربری و/يا گذرواژه صحيح نمی‌باشد!.
        /// </summary>
        public static string Error003 {
            get {
                return ResourceManager.GetString("Error003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن همراه تکراری است! لطفا از شماره تلفن همراه ديگری استفاده نماييد..
        /// </summary>
        public static string Error004 {
            get {
                return ResourceManager.GetString("Error004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی، نشانی پست الکترونيکی شما هنوز مورد تاييد قرار نگرفته است! لطفا به صندوق پست الکترونيکی خود مراجعه کرده و در نامه الکترونيکی ارسال شده، بر روی لينکی که در آن قرار دارد، کليک نماييد..
        /// </summary>
        public static string Error005 {
            get {
                return ResourceManager.GetString("Error005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی، متاسفانه در حال حاضر، شما قادر به ورود به پايگاه نمی‌باشيد! لطفا در اين خصوص با مسوولين پايگاه تماس حاصل فرماييد..
        /// </summary>
        public static string Error006 {
            get {
                return ResourceManager.GetString("Error006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صحت نشانی پست الکترونيکی شما قبلا تاييد شده است..
        /// </summary>
        public static string Error007 {
            get {
                return ResourceManager.GetString("Error007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه جاری را به درستی وارد نکرده‌ايد!.
        /// </summary>
        public static string Error008 {
            get {
                return ResourceManager.GetString("Error008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تاييد مربوط به شماره تلفن همراه صحيح نمی‌باشد!.
        /// </summary>
        public static string Error009 {
            get {
                return ResourceManager.GetString("Error009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی معتبر نمی‌باشد! لطفا مجددا و با دقت آنرا وارد نماييد..
        /// </summary>
        public static string Error010 {
            get {
                return ResourceManager.GetString("Error010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمليات ثبت‌نام با موفقيت انجام گرديد و برای شناسايی نشانی پست الکترونيکی شما، هم‌اکنون ايميلی برايتان ارسال شد..
        /// </summary>
        public static string Information001 {
            get {
                return ResourceManager.GetString("Information001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجددا نامه الکترونيکی برای تاييد صحت ايميل شما ارسال گرديد..
        /// </summary>
        public static string Information002 {
            get {
                return ResourceManager.GetString("Information002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بنابه درخواست شما، گذرواژه جديدی ايجاد و برای شما ارسال گرديد. لطفا با گذرواژه جديد وارد پايگاه شده و توصيه می‌کنيم در اولين فرصت، آنرا تغيير دهيد..
        /// </summary>
        public static string Information003 {
            get {
                return ResourceManager.GetString("Information003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه جديد برای کاربر ثبت گرديد..
        /// </summary>
        public static string Information004 {
            get {
                return ResourceManager.GetString("Information004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه جديد با موفقيت ثبت گرديد..
        /// </summary>
        public static string Information005 {
            get {
                return ResourceManager.GetString("Information005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پيام کوتاهی به شماره همراه شما برای تاييد صحت آن ارسال گرديد..
        /// </summary>
        public static string Information006 {
            get {
                return ResourceManager.GetString("Information006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صحت شماره تلفن همراه شما تاييد گرديد..
        /// </summary>
        public static string Information007 {
            get {
                return ResourceManager.GetString("Information007", resourceCulture);
            }
        }
    }
}
